import assert from 'node:assert/strict';
import test from 'node:test';
import {createAsset,importSharedAsset,MemoryAssetRepository,cueAssetUrl} from '../lib/assets.ts';
import {createAuthoringService,MemoryAuthoringRepository} from '../lib/authoring.ts';
import {buildSharedLibraryPayload,type SharedLibrarySnapshot} from '../lib/shared-library.ts';

const BARECHU='efa9fad4-f7d5-4091-a708-82103028861b';
const png=()=>new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64'));
const headers=()=>new Headers({'x-asset-name':encodeURIComponent('Service artwork'),'x-asset-alt':encodeURIComponent('A woven tree')});
const measurement={viewportWidth:1920,viewportHeight:1080,fontsReady:true,overflow:false,rendererVersion:'asset-integration-test',measuredAt:Date.now()};

test('artwork stays private until exact reviewed publication and remains usable in historical output',async()=>{
 const assets=new MemoryAssetRepository(),asset=await createAsset(png(),headers(),'editor',assets),repo=new MemoryAuthoringRepository(assets),service=createAuthoringService(repo);
 const imported=await service.operation('import_cue',{cueId:BARECHU},'editor') as {draft:{id:string;version:number;content:{mode:string;hebrewGroups:Array<{sourceId:string;blockIds:string[]}>};sourceSnapshots:Array<{id:string;blocks:Array<{id:string;he?:string}>}>}};
 const group=imported.draft.content.hebrewGroups[0],block=imported.draft.sourceSnapshots.find(source=>source.id===group.sourceId)!.blocks.find(item=>item.id===group.blockIds[0])!;
 const variant=await service.operation('create_local_variant',{draftId:imported.draft.id,label:'CRC local wording',overrides:[{sourceId:group.sourceId,blockId:block.id,channel:'he',localText:`${block.he}׃`}]},'editor') as {draft:{id:string;version:number;presentation:Record<string,unknown>}};
 const updated=await service.operation('update_draft',{draftId:variant.draft.id,expectedVersion:variant.draft.version,patch:{presentation:{imageAssetId:asset.id}}},'editor') as {draft:{id:string;version:number}};
 const preview=await service.operation('preview_draft',{draftId:updated.draft.id,expectedVersion:updated.draft.version},'editor') as {previewId:string;cueHash:string;cue:{presentation?:{imageAssetId?:string;imageAssetUrl?:string}}};
 assert.equal(preview.cue.presentation?.imageAssetId,asset.id);assert.equal(preview.cue.presentation?.imageAssetUrl,undefined);assert.match((await cueAssetUrl(preview.cue,'preview',assets))!,/\/preview$/);assert.equal((await assets.get(asset.id))!.published,false);
 await assert.rejects(service.operation('publish_draft',{draftId:updated.draft.id,expectedVersion:updated.draft.version,previewId:preview.previewId},'publisher'),/review/i);assert.equal((await assets.get(asset.id))!.published,false);
 await service.operation('review_draft',{draftId:updated.draft.id,expectedVersion:updated.draft.version,previewId:preview.previewId,browserMeasurement:measurement,humanApproved:true},'reviewer');
 await assets.setArchived(asset.id,1,true,'editor',Date.now());await assert.rejects(service.operation('publish_draft',{draftId:updated.draft.id,expectedVersion:updated.draft.version,previewId:preview.previewId},'publisher'),/unavailable/i);assert.equal((await assets.get(asset.id))!.published,false);
 await assets.setArchived(asset.id,2,false,'editor',Date.now());const published=await service.operation('publish_draft',{draftId:updated.draft.id,expectedVersion:updated.draft.version,previewId:preview.previewId},'publisher') as {revision:{cueHash:string;cue:{presentation?:{imageAssetId?:string;imageAssetUrl?:string}}}};
 assert.equal(published.revision.cueHash,preview.cueHash);assert.equal(published.revision.cue.presentation?.imageAssetId,asset.id);assert.equal(published.revision.cue.presentation?.imageAssetUrl,undefined);assert.doesNotMatch(JSON.stringify(published.revision.cue),/\/preview/);assert.equal((await assets.get(asset.id))!.published,true);
 await assets.setArchived(asset.id,3,true,'editor',Date.now());const active=(await service.publishedCues()).find(cue=>cue.id===updated.draft.id)!;assert.equal(active.presentation?.imageAssetId,asset.id);assert.match((await cueAssetUrl(active,'published',assets))!,/\/content$/);
});

test('shared preview imports immutable CRC artwork once before independent TBI customization',async()=>{
 const crcAssets=new MemoryAssetRepository(),asset=await createAsset(png(),headers(),'crc',crcAssets);await crcAssets.markPublished(asset.id,Date.now());
 const crcRepo=new MemoryAuthoringRepository(crcAssets),crc=createAuthoringService(crcRepo),imported=await crc.operation('import_cue',{cueId:BARECHU},'crc') as {draft:{id:string;version:number;content:{hebrewGroups:Array<{sourceId:string;blockIds:string[]}>};sourceSnapshots:Array<{id:string;blocks:Array<{id:string;he?:string}>}>}};
 const group=imported.draft.content.hebrewGroups[0],block=imported.draft.sourceSnapshots.find(source=>source.id===group.sourceId)!.blocks.find(item=>item.id===group.blockIds[0])!,variant=await crc.operation('create_local_variant',{draftId:imported.draft.id,label:'CRC local wording',overrides:[{sourceId:group.sourceId,blockId:block.id,channel:'he',localText:`${block.he}׃`}]},'crc') as {draft:{id:string;version:number}};
 const updated=await crc.operation('update_draft',{draftId:variant.draft.id,expectedVersion:variant.draft.version,patch:{presentation:{imageAssetId:asset.id}}},'crc') as {draft:{id:string;version:number}},preview=await crc.operation('preview_draft',{draftId:updated.draft.id,expectedVersion:updated.draft.version},'crc') as {previewId:string;cueHash:string};await crc.operation('review_draft',{draftId:updated.draft.id,expectedVersion:updated.draft.version,previewId:preview.previewId,browserMeasurement:measurement,humanApproved:true},'crc');await crc.operation('publish_draft',{draftId:updated.draft.id,expectedVersion:updated.draft.version,previewId:preview.previewId},'crc');
 const cue=(await crc.publishedCues()).find(item=>item.id===updated.draft.id)!,payload=buildSharedLibraryPayload({cues:[cue],version:'asset-variant'}),snapshot:SharedLibrarySnapshot={available:true,configured:true,stale:false,refreshedAt:Date.now(),payload},tbiAssets=new MemoryAssetRepository();let fetches=0;
 const fetcher:typeof fetch=async()=>{fetches++;const stored=(await crcAssets.get(asset.id))!;return new Response(Uint8Array.from(stored.data).buffer,{headers:{'content-length':String(stored.bytes),'x-asset-name':encodeURIComponent(stored.name),'x-asset-alt':encodeURIComponent(stored.altText)}})};
 const importer=(id:string,actor:string)=>importSharedAsset(id,actor,tbiAssets,{WORKSPACE_ID:'temple-bnai-israel-kalamazoo',CRC_SHARED_LIBRARY_URL:'https://crc.example/api/shared-library',SHARED_LIBRARY_IMPORT_KEY:'x'.repeat(32)},fetcher),tbi=createAuthoringService(new MemoryAuthoringRepository(tbiAssets),undefined,{get:async()=>snapshot},importer);
 const sharedPreview=await tbi.operation('preview_shared_cue',{cueId:cue.id},'simone') as {cueHash:string;cue:{presentation?:{imageAssetId?:string;imageAssetUrl?:string}}};assert.equal(sharedPreview.cue.presentation?.imageAssetId,asset.id);assert.equal(sharedPreview.cue.presentation?.imageAssetUrl,undefined);assert.equal(fetches,1);assert.equal((await tbiAssets.get(asset.id))!.published,false);
 const copied=await tbi.operation('customize_shared_cue',{cueId:cue.id,expectedCueHash:sharedPreview.cueHash},'simone') as {draft:{content:{mode:string};activeRevision:null;presentation:{imageAssetId?:string}}};assert.equal(fetches,1,'customize reuses the hash-verified local bytes imported for preview');assert.equal(copied.draft.content.mode,'local-variant');assert.equal(copied.draft.presentation.imageAssetId,asset.id);assert.equal(copied.draft.activeRevision,null);
});
