/**
 * Google sign-in core module, against a fake issuer. No network: `googleDependencies.fetch`
 * is swapped for a handler that answers the discovery document, the JWKS and the token
 * endpoint for `https://issuer.test`, checks PKCE S256 and the code, and returns an RS256
 * id_token signed with a key generated by `node:crypto` (JWK via `KeyObject.export`).
 */
import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash,generateKeyPairSync,sign} from 'node:crypto';
import type {AccessMember} from '../lib/access.ts';
import {
 GOOGLE_CALLBACK_PATH,GOOGLE_SCOPES,REGISTERED_ORIGINS,
 GoogleMismatchError,GoogleUnavailableError,
 beginGoogleFlow,completeGoogleCallback,confirmGoogleFlow,googleConfiguration,googleDependencies,
 googleReturnPath,googleSignInAvailability,resetGoogleConfiguration,resolveGoogleCallback,
} from '../lib/google-sign-in.ts';
import type {GoogleIdentity,GoogleIdentityStore,SignInFlow} from '../lib/google-sign-in.ts';

const CLIENT_ID='client-id.apps.googleusercontent.test';
const CLIENT_SECRET='client-secret-value';
const CREDENTIALS={GOOGLE_OAUTH_CLIENT_ID:CLIENT_ID,GOOGLE_OAUTH_CLIENT_SECRET:CLIENT_SECRET} as const;
const CRC_ORIGIN='https://crc-overlays.vercel.app';
const REDIRECT=`${CRC_ORIGIN}${GOOGLE_CALLBACK_PATH}`;

// ---------------------------------------------------------------- fake issuer

const base64url=(value:object)=>Buffer.from(JSON.stringify(value)).toString('base64url');
const s256=(value:string)=>createHash('sha256').update(value).digest('base64url');

type IssuerOptions={discoveryStatus?:number};
type TokenObservation={code:string;codeVerifier:string;redirectUri:string;clientId:string};

function fakeIssuer(options:IssuerOptions={}){
 const origin='https://issuer.test';
 const {publicKey,privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});
 const jwk=publicKey.export({format:'jwk'}) as Record<string,string>;
 const authorized=new Map<string,{challenge:string;method:string;nonce:string;redirectUri:string}>();
 const tokenCalls:TokenObservation[]=[];
 const counts={discovery:0,jwks:0,token:0};
 /** Claims merged over the defaults, so a test can corrupt exactly one of them. */
 const claimOverrides:Record<string,unknown>={};
 const profile={subject:'google-subject-1',email:'Owner@Crc.Example',emailVerified:true};

 /** Stands in for the browser visiting Google: records the challenge, hands back a code. */
 function authorize(url:URL){
  const code=`code-${authorized.size+1}`;
  authorized.set(code,{
   challenge:url.searchParams.get('code_challenge')||'',
   method:url.searchParams.get('code_challenge_method')||'',
   nonce:url.searchParams.get('nonce')||'',
   redirectUri:url.searchParams.get('redirect_uri')||'',
  });
  return code;
 }

 function idToken(nonce:string){
  const issuedAt=Math.floor(Date.now()/1000);
  const payload={iss:origin,aud:CLIENT_ID,sub:profile.subject,iat:issuedAt,exp:issuedAt+300,nonce,email:profile.email,email_verified:profile.emailVerified,name:'Owner Example',...claimOverrides};
  const header=base64url({alg:'RS256',typ:'JWT',kid:'test-key'});
  const body=base64url(payload);
  const signature=sign('sha256',Buffer.from(`${header}.${body}`),privateKey).toString('base64url');
  return `${header}.${body}.${signature}`;
 }

 const handler=async(input:string,init?:{body?:unknown;method?:string}):Promise<Response>=>{
  const url=new URL(String(input));
  if(url.pathname==='/.well-known/openid-configuration'){
   counts.discovery++;
   if(options.discoveryStatus&&options.discoveryStatus!==200)return new Response('upstream failure',{status:options.discoveryStatus});
   return Response.json({
    issuer:origin,
    authorization_endpoint:`${origin}/authorize`,
    token_endpoint:`${origin}/token`,
    jwks_uri:`${origin}/jwks`,
    response_types_supported:['code'],
    subject_types_supported:['public'],
    id_token_signing_alg_values_supported:['RS256'],
    grant_types_supported:['authorization_code'],
    code_challenge_methods_supported:['S256'],
    scopes_supported:['openid','email','profile'],
   });
  }
  if(url.pathname==='/jwks'){counts.jwks++;return Response.json({keys:[{...jwk,kid:'test-key',alg:'RS256',use:'sig'}]})}
  if(url.pathname==='/token'){
   counts.token++;
   const body=new URLSearchParams(typeof init?.body==='string'?init.body:String(init?.body??''));
   const code=body.get('code')||'';const codeVerifier=body.get('code_verifier')||'';
   const record=authorized.get(code);
   if(!record)return Response.json({error:'invalid_grant'},{status:400});
   if(record.method!=='S256'||s256(codeVerifier)!==record.challenge)return Response.json({error:'invalid_grant'},{status:400});
   if(body.get('redirect_uri')!==record.redirectUri)return Response.json({error:'invalid_grant'},{status:400});
   authorized.delete(code);
   tokenCalls.push({code,codeVerifier,redirectUri:body.get('redirect_uri')||'',clientId:body.get('client_id')||''});
   return Response.json({access_token:'access-token-value',token_type:'bearer',expires_in:3600,id_token:idToken(record.nonce)});
  }
  return new Response('not found',{status:404});
 };

 return {origin,authorize,claimOverrides,profile,counts,tokenCalls,authorized,fetch:handler as unknown as typeof fetch};
}

async function withIssuer(issuer:ReturnType<typeof fakeIssuer>,run:()=>Promise<void>){
 const before={fetch:googleDependencies.fetch,issuer:googleDependencies.issuer,now:googleDependencies.now};
 googleDependencies.fetch=issuer.fetch;googleDependencies.issuer=issuer.origin;
 resetGoogleConfiguration();
 try{await run()}finally{Object.assign(googleDependencies,before);resetGoogleConfiguration()}
}

const envNames=['PUBLIC_BASE_URL','GOOGLE_OAUTH_CLIENT_ID','GOOGLE_OAUTH_CLIENT_SECRET'] as const;
async function withEnvironment(values:Partial<Record<(typeof envNames)[number],string|undefined>>,run:()=>Promise<void>|void){
 const before=Object.fromEntries(envNames.map(name=>[name,process.env[name]]));
 try{for(const name of envNames){const value=values[name];if(value===undefined)Reflect.deleteProperty(process.env,name);else Reflect.set(process.env,name,value)}await run()}
 finally{for(const name of envNames){const value=before[name];if(value===undefined)Reflect.deleteProperty(process.env,name);else Reflect.set(process.env,name,value)}}
}

// ------------------------------------------------------------------ fake store

const member=(id:string,email:string,enabled=true):AccessMember=>({id,email,name:id,role:'editor',enabled});

class FakeStore implements GoogleIdentityStore {
 members=new Map<string,AccessMember>();
 identities=new Map<string,{memberId:string;email:string;linkedAt:number}>();
 invitations=new Map<string,{memberId:string;email:string}>();
 flows=new Map<string,{payload:SignInFlow;expiresAt:number}>();
 linkCalls=0;unlinkCalls=0;
 static key(identity:GoogleIdentity){return `${identity.provider}\n${identity.issuer}\n${identity.subject}`}
 add(record:AccessMember){this.members.set(record.id,record);return record}
 async identityForMember(memberId:string){
  for(const value of this.identities.values())if(value.memberId===memberId)return {email:value.email,linkedAt:value.linkedAt};
  return null;
 }
 async memberForIdentity(identity:GoogleIdentity){
  const row=this.identities.get(FakeStore.key(identity));if(!row)return null;
  const found=this.members.get(row.memberId);return found?{...found}:null;
 }
 async linkIdentity(memberId:string,identity:GoogleIdentity,now:number){
  this.linkCalls++;
  for(const [key,value] of this.identities)if(value.memberId===memberId)this.identities.delete(key);
  this.identities.set(FakeStore.key(identity),{memberId,email:identity.email,linkedAt:now});
 }
 async unlinkIdentity(memberId:string){
  this.unlinkCalls++;
  for(const [key,value] of this.identities)if(value.memberId===memberId)this.identities.delete(key);
 }
 async putSignInFlow(hash:string,payload:SignInFlow,expiresAt:number){this.flows.set(hash,{payload,expiresAt})}
 async takeSignInFlow(hash:string,now:number){
  const row=this.flows.get(hash);if(!row)return null;this.flows.delete(hash);
  return row.expiresAt<=now?null:row.payload;
 }
 async memberById(memberId:string){const found=this.members.get(memberId);return found?{...found}:null}
 async invitationTarget(inviteHash:string){return this.invitations.get(inviteHash)??null}
 requests:Array<{identity:GoogleIdentity;now:number}>=[];
 async memberByEmail(email:string){for(const found of this.members.values())if(found.email.toLowerCase()===email.trim().toLowerCase())return {...found};return null}
 async recordAccessRequest(identity:GoogleIdentity,now:number){this.requests.push({identity,now})}
}

const identityOf=(email:string,subject='google-subject-1',emailVerified=true):GoogleIdentity=>({provider:'google',issuer:'https://issuer.test',subject,email,emailVerified});
const flowOf=(over:Partial<SignInFlow>&{kind:SignInFlow['kind']}):SignInFlow=>({createdAt:1,codeVerifier:'verifier',state:'state',nonce:'nonce',redirectUri:REDIRECT,...over});

// ------------------------------------------------------------------- host gating

test('availability is limited to registered origins that agree with the canonical origin',async()=>{
 const at=(origin:string)=>googleSignInAvailability(new Request(`${origin}/api/access`),CREDENTIALS);

 await withEnvironment({PUBLIC_BASE_URL:CRC_ORIGIN},()=>{
  const crc=at(CRC_ORIGIN);
  assert.deepEqual(crc,{available:true,reason:null,redirectUri:REDIRECT});
  // A preview deployment gets a generated hostname that cannot be registered with Google.
  assert.deepEqual(at('https://crc-overlays-git-x.vercel.app'),{available:false,reason:'preview',redirectUri:REDIRECT});
  // Registered host, but PUBLIC_BASE_URL names the other workspace: fail closed.
  assert.deepEqual(at('https://tbi-overlays.vercel.app'),{available:false,reason:'misconfigured',redirectUri:REDIRECT});
  // The redirect URI is never built from the Host header alone.
  assert.equal(at('https://crc-overlays-git-x.vercel.app').redirectUri,REDIRECT);
 });

 await withEnvironment({PUBLIC_BASE_URL:'https://tbi-overlays.vercel.app'},()=>{
  assert.deepEqual(at('https://tbi-overlays.vercel.app'),{available:true,reason:null,redirectUri:`https://tbi-overlays.vercel.app${GOOGLE_CALLBACK_PATH}`});
 });

 // Loopback development: canonicalOrigin echoes the request origin, no PUBLIC_BASE_URL.
 await withEnvironment({PUBLIC_BASE_URL:undefined},()=>{
  assert.deepEqual(at('http://localhost:5175'),{available:true,reason:null,redirectUri:`http://localhost:5175${GOOGLE_CALLBACK_PATH}`});
  assert.deepEqual(at('http://localhost:3000'),{available:true,reason:null,redirectUri:`http://localhost:3000${GOOGLE_CALLBACK_PATH}`});
  assert.deepEqual(at('http://localhost:4000'),{available:false,reason:'preview',redirectUri:`http://localhost:4000${GOOGLE_CALLBACK_PATH}`});
 });

 // No credentials at all: the button is hidden, not disabled.
 await withEnvironment({PUBLIC_BASE_URL:CRC_ORIGIN,GOOGLE_OAUTH_CLIENT_ID:undefined,GOOGLE_OAUTH_CLIENT_SECRET:undefined},()=>{
  assert.deepEqual(googleSignInAvailability(new Request(`${CRC_ORIGIN}/api/access`)),{available:false,reason:'unconfigured',redirectUri:REDIRECT});
  assert.equal(googleSignInAvailability(new Request(`${CRC_ORIGIN}/api/access`),{GOOGLE_OAUTH_CLIENT_ID:CLIENT_ID}).reason,'unconfigured');
 });

 assert.deepEqual([...REGISTERED_ORIGINS],[CRC_ORIGIN,'https://overlays.centralreform.org','https://tbi-overlays.vercel.app','https://overlays.templebnaiisrael.com','http://localhost:3000','http://localhost:5175']);
 assert.equal(googleReturnPath('no_access'),'/access?google=no_access');
});

// --------------------------------------------------------------- authorization

test('the authorization URL carries the three scopes, PKCE S256 and select_account only',async()=>{
 const issuer=fakeIssuer();
 await withIssuer(issuer,async()=>{
  const config=await googleConfiguration(CREDENTIALS);
  const {url,flow}=await beginGoogleFlow(config,{redirectUri:REDIRECT,kind:'link',memberId:'member-1'});
  assert.equal(url.origin+url.pathname,'https://issuer.test/authorize');
  assert.equal(url.searchParams.get('scope'),GOOGLE_SCOPES);
  assert.equal(url.searchParams.get('redirect_uri'),REDIRECT);
  assert.equal(url.searchParams.get('response_type'),'code');
  assert.equal(url.searchParams.get('client_id'),CLIENT_ID);
  assert.equal(url.searchParams.get('prompt'),'select_account');
  assert.equal(url.searchParams.get('code_challenge_method'),'S256');
  assert.equal(url.searchParams.get('state'),flow.state);
  assert.equal(url.searchParams.get('nonce'),flow.nonce);
  assert.equal(url.searchParams.get('code_challenge'),s256(flow.codeVerifier));
  assert.notEqual(url.searchParams.get('code_challenge'),flow.codeVerifier);
  assert.equal(url.searchParams.get('access_type'),null,'no refresh token is ever requested');
  assert.equal(flow.kind,'link');assert.equal(flow.memberId,'member-1');assert.equal(flow.inviteHash,undefined);
  // Discovery is memoized: a second flow makes no second discovery request.
  await beginGoogleFlow(await googleConfiguration(CREDENTIALS),{redirectUri:REDIRECT,kind:'signin'});
  assert.equal(issuer.counts.discovery,1);
 });
});

test('a completed callback yields the verified identity and proves the code verifier',async()=>{
 const issuer=fakeIssuer();
 await withIssuer(issuer,async()=>{
  const config=await googleConfiguration(CREDENTIALS);
  const {url,flow}=await beginGoogleFlow(config,{redirectUri:REDIRECT,kind:'signin'});
  const code=issuer.authorize(url);
  const identity=await completeGoogleCallback(config,new URL(`${REDIRECT}?code=${code}&state=${flow.state}`),flow);
  assert.deepEqual(identity,{provider:'google',issuer:'https://issuer.test',subject:'google-subject-1',email:'owner@crc.example',emailVerified:true,name:'Owner Example'});
  assert.deepEqual(issuer.tokenCalls,[{code,codeVerifier:flow.codeVerifier,redirectUri:REDIRECT,clientId:CLIENT_ID}]);
  assert.equal(issuer.counts.token,1);
  // The single-use code is spent; a replay is a mismatch, not a second identity.
  await assert.rejects(completeGoogleCallback(config,new URL(`${REDIRECT}?code=${code}&state=${flow.state}`),flow),GoogleMismatchError);
 });
});

test('an unverified Google email still produces an identity, flagged as unverified',async()=>{
 const issuer=fakeIssuer();
 issuer.profile.emailVerified=false;
 await withIssuer(issuer,async()=>{
  const config=await googleConfiguration(CREDENTIALS);
  const {url,flow}=await beginGoogleFlow(config,{redirectUri:REDIRECT,kind:'signin'});
  const identity=await completeGoogleCallback(config,new URL(`${REDIRECT}?code=${issuer.authorize(url)}&state=${flow.state}`),flow);
  assert.equal(identity.emailVerified,false);
 });
});

for(const failure of [
 {name:'nonce mismatch',claims:{nonce:'not-the-nonce'}},
 {name:'wrong audience',claims:{aud:'another-client.apps.googleusercontent.test'}},
 {name:'expired id_token',claims:{exp:Math.floor(Date.now()/1000)-3600}},
 {name:'wrong issuer',claims:{iss:'https://evil.test'}},
]) test(`${failure.name} is a mismatch, never a sign-in`,async()=>{
 const issuer=fakeIssuer();
 await withIssuer(issuer,async()=>{
  const config=await googleConfiguration(CREDENTIALS);
  const {url,flow}=await beginGoogleFlow(config,{redirectUri:REDIRECT,kind:'signin'});
  const code=issuer.authorize(url);
  Object.assign(issuer.claimOverrides,failure.claims);
  await assert.rejects(completeGoogleCallback(config,new URL(`${REDIRECT}?code=${code}&state=${flow.state}`),flow),GoogleMismatchError);
 });
});

test('a state that does not match the stored flow never reaches the token endpoint',async()=>{
 const issuer=fakeIssuer();
 await withIssuer(issuer,async()=>{
  const config=await googleConfiguration(CREDENTIALS);
  const {url,flow}=await beginGoogleFlow(config,{redirectUri:REDIRECT,kind:'signin'});
  const code=issuer.authorize(url);
  await assert.rejects(completeGoogleCallback(config,new URL(`${REDIRECT}?code=${code}&state=someone-elses-state`),flow),GoogleMismatchError);
  assert.equal(issuer.counts.token,0);
 });
});

test('a failing discovery document is unavailable, not an exception leaking to the route',async()=>{
 const issuer=fakeIssuer({discoveryStatus:500});
 await withIssuer(issuer,async()=>{
  await assert.rejects(googleConfiguration(CREDENTIALS),GoogleUnavailableError);
  // A failed discovery is not memoized, so the next request retries.
  await assert.rejects(googleConfiguration(CREDENTIALS),GoogleUnavailableError);
  assert.equal(issuer.counts.discovery,2);
  await assert.rejects(googleConfiguration({}),GoogleUnavailableError);
 });
});

// --------------------------------------------------------------- decision table

test('signin: linked and enabled signs in, linked and disabled is removed, unlinked is no_access',async()=>{
 const store=new FakeStore();
 const owner=store.add(member('member-1','owner@crc.example'));
 const identity=identityOf('owner@crc.example');
 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'signin'}),identity,store,10),{code:'no_access'});
 assert.equal(store.linkCalls,0,'an email match alone never links');

 await store.linkIdentity(owner.id,identity,5);
 const signedIn=await resolveGoogleCallback(flowOf({kind:'signin'}),identity,store,10);
 assert.equal(signedIn.code,'signed_in');
 if(signedIn.code==='signed_in')assert.equal(signedIn.member.id,'member-1');

 store.members.set('member-1',{...owner,enabled:false});
 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'signin'}),identity,store,10),{code:'removed'});
 assert.equal(store.linkCalls,1,'only the explicit link wrote');
});

test('link: idempotent, refuses another member, binds a verified same email, else confirms',async()=>{
 const store=new FakeStore();
 store.add(member('member-1','owner@crc.example'));
 store.add(member('member-2','other@crc.example'));
 const flow=flowOf({kind:'link',memberId:'member-1'});

 // Not linked, verified, same email: the one write the table allows.
 const linked=await resolveGoogleCallback(flow,identityOf('Owner@crc.example'),store,20);
 assert.equal(linked.code,'linked');
 assert.equal(store.linkCalls,1);
 assert.deepEqual(await store.identityForMember('member-1'),{email:'Owner@crc.example',linkedAt:20});

 // Already linked to this member: idempotent notice, no second write.
 assert.equal((await resolveGoogleCallback(flow,identityOf('Owner@crc.example'),store,21)).code,'linked');
 assert.equal(store.linkCalls,1);

 // Linked to somebody else here.
 await store.linkIdentity('member-2',identityOf('someone@else.example','google-subject-2'),22);
 assert.deepEqual(await resolveGoogleCallback(flow,identityOf('someone@else.example','google-subject-2'),store,23),{code:'already_linked'});

 // Email differs, or is unverified: hold for the confirmation card, write nothing.
 const fresh=new FakeStore();fresh.add(member('member-1','owner@crc.example'));
 const differs=await resolveGoogleCallback(flow,identityOf('personal@gmail.example','google-subject-3'),fresh,24);
 assert.equal(differs.code,'confirm');
 if(differs.code==='confirm'){assert.equal(differs.flow.pending?.status,'confirm');assert.equal(differs.flow.pending?.identity.email,'personal@gmail.example');assert.equal(differs.flow.kind,'link')}
 assert.equal((await resolveGoogleCallback(flow,identityOf('owner@crc.example','google-subject-4',false),fresh,25)).code,'confirm');
 assert.equal(fresh.linkCalls,0);
 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'link'}),identityOf('owner@crc.example'),fresh,26),{code:'mismatch'});
});

test('redeem: an invalid invitation stops, a foreign identity stops, a matching one redeems',async()=>{
 const store=new FakeStore();
 store.add(member('member-1','invited@crc.example',false));
 store.add(member('member-2','other@crc.example'));
 store.invitations.set('invite-hash',{memberId:'member-1',email:'invited@crc.example'});
 const flow=flowOf({kind:'redeem',inviteHash:'invite-hash'});

 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'redeem',inviteHash:'gone'}),identityOf('invited@crc.example'),store,30),{code:'invite_invalid'});
 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'redeem'}),identityOf('invited@crc.example'),store,30),{code:'mismatch'});

 // Verified email equal to the invited email: redemption is returned, never performed here.
 assert.deepEqual(await resolveGoogleCallback(flow,identityOf('Invited@CRC.example'),store,31),{code:'redeem',identity:identityOf('Invited@CRC.example'),inviteHash:'invite-hash'});
 assert.equal(store.linkCalls,0,'resolveGoogleCallback never redeems or links on the redeem path');

 // Already linked to somebody else here: the invitation stays unused.
 await store.linkIdentity('member-2',identityOf('invited@crc.example','google-subject-9'),32);
 assert.deepEqual(await resolveGoogleCallback(flow,identityOf('invited@crc.example','google-subject-9'),store,33),{code:'already_linked'});
 assert.ok(store.invitations.has('invite-hash'));

 // Already linked to the invitation's own member: redeem again (the link is the authorization).
 await store.linkIdentity('member-1',identityOf('anything@else.example','google-subject-8'),34);
 assert.equal((await resolveGoogleCallback(flow,identityOf('anything@else.example','google-subject-8'),store,35)).code,'redeem');

 // Email differs or is unverified: confirm, no writes.
 const fresh=new FakeStore();
 fresh.add(member('member-1','invited@crc.example',false));
 fresh.invitations.set('invite-hash',{memberId:'member-1',email:'invited@crc.example'});
 assert.equal((await resolveGoogleCallback(flow,identityOf('personal@gmail.example'),fresh,36)).code,'confirm');
 assert.equal((await resolveGoogleCallback(flow,identityOf('invited@crc.example','google-subject-7',false),fresh,37)).code,'confirm');
 assert.equal(fresh.linkCalls,0);
});

test('confirming a held flow binds it; cancelling and an empty hold write nothing',async()=>{
 const store=new FakeStore();
 store.add(member('member-1','owner@crc.example'));
 store.add(member('member-2','other@crc.example'));
 const identity=identityOf('personal@gmail.example','google-subject-5',false);
 const held=flowOf({kind:'link',memberId:'member-1',pending:{identity,status:'confirm'}});

 assert.deepEqual(await confirmGoogleFlow(held,'cancel',store,40),{code:'cancelled'});
 assert.equal(store.linkCalls,0);
 assert.deepEqual(await confirmGoogleFlow(flowOf({kind:'link',memberId:'member-1'}),'link',store,40),{code:'mismatch'});
 assert.equal(store.linkCalls,0);

 const linked=await confirmGoogleFlow(held,'link',store,41);
 assert.equal(linked.code,'linked');
 assert.equal(store.linkCalls,1);
 assert.deepEqual(await store.identityForMember('member-1'),{email:'personal@gmail.example',linkedAt:41});
 // Confirming twice is idempotent.
 assert.equal((await confirmGoogleFlow(held,'link',store,42)).code,'linked');
 assert.equal(store.linkCalls,1);

 // Held for somebody else's identity in the meantime.
 const other=identityOf('taken@gmail.example','google-subject-6',false);
 await store.linkIdentity('member-2',other,43);
 assert.deepEqual(await confirmGoogleFlow(flowOf({kind:'link',memberId:'member-1',pending:{identity:other,status:'confirm'}}),'link',store,44),{code:'already_linked'});

 // Redeem hold: confirming returns the redeem instruction, still without writing.
 store.add(member('member-3','invited@crc.example',false));
 store.invitations.set('invite-hash',{memberId:'member-3',email:'invited@crc.example'});
 const redeemHold=flowOf({kind:'redeem',inviteHash:'invite-hash',pending:{identity:identityOf('personal2@gmail.example','google-subject-10',false),status:'confirm'}});
 assert.deepEqual(await confirmGoogleFlow(redeemHold,'link',store,45),{code:'redeem',identity:identityOf('personal2@gmail.example','google-subject-10',false),inviteHash:'invite-hash'});
 assert.equal(store.linkCalls,2);
 assert.deepEqual(await confirmGoogleFlow(flowOf({kind:'redeem',pending:{identity,status:'confirm'}}),'link',store,46),{code:'mismatch'});
});

test('one Google identity maps independently in each congregation database',async()=>{
 const crc=new FakeStore();const tbi=new FakeStore();
 crc.add(member('crc-owner','daniel@centralreform.org'));
 tbi.add({...member('tbi-operator','daniel@centralreform.org'),role:'operator'});
 const identity=identityOf('daniel@centralreform.org');

 await crc.linkIdentity('crc-owner',identity,50);
 const crcSignIn=await resolveGoogleCallback(flowOf({kind:'signin'}),identity,crc,51);
 assert.equal(crcSignIn.code,'signed_in');
 // The same identity is unknown in TBI until TBI's own administrator invites it.
 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'signin'}),identity,tbi,51),{code:'no_access'});

 await tbi.linkIdentity('tbi-operator',identity,52);
 const tbiSignIn=await resolveGoogleCallback(flowOf({kind:'signin'}),identity,tbi,53);
 assert.equal(tbiSignIn.code,'signed_in');
 if(crcSignIn.code==='signed_in'&&tbiSignIn.code==='signed_in'){
  assert.equal(crcSignIn.member.role,'editor');
  assert.equal(tbiSignIn.member.role,'operator');
 }
 assert.equal(crc.members.size,1);assert.equal(tbi.members.size,1,'nothing ever creates a member');
});

test('signin: an unknown verified account is recorded as a request; an unverified one or an enabled member\'s address is not',async()=>{
 const store=new FakeStore();
 assert.equal(googleReturnPath('requested'),'/access?google=requested');
 const stranger=identityOf('stranger@example.org','google-subject-9');
 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'signin'}),stranger,store,10),{code:'requested'});
 assert.equal(store.requests.length,1);
 assert.equal(store.requests[0].identity.subject,'google-subject-9');
 assert.equal(store.requests[0].now,10);
 assert.equal(store.linkCalls,0,'a request never links');
 assert.equal(store.members.size,0,'a request never creates a member');

 const unverified=identityOf('unverified@example.org','google-subject-8',false);
 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'signin'}),unverified,store,11),{code:'no_access'});
 assert.equal(store.requests.length,1,'an unverified address is not queued');

 store.add(member('member-2','known@crc.example'));
 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'signin'}),identityOf('Known@CRC.example','google-subject-7'),store,12),{code:'no_access'},'an enabled member links from their own account instead');
 assert.equal(store.requests.length,1);

 store.add(member('member-3','invited@crc.example',false));
 assert.deepEqual(await resolveGoogleCallback(flowOf({kind:'signin'}),identityOf('invited@crc.example','google-subject-6'),store,13),{code:'requested'},'an invited member who never opened the link may ask instead');
 assert.equal(store.requests.length,2);
});
