import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import {sourcePinFor,type AuthoringSource,type Draft,type DraftContent} from '../lib/authoring-model.ts';
import {MemoryAuthoringRepository} from '../lib/authoring.ts';
import {MemorySourceReviewRepository,createSourceReviewService,type SourceChangeRecord,type SourceChangeSummary} from '../lib/source-review.ts';

const BARECHU='efa9fad4-f7d5-4091-a708-82103028861b';
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');

type ScanResult={detected:number;coverage:{authoredDrafts:number;unopenedPublished:{total:number;verifiable:number;unverifiable:number;message:string}};records:SourceChangeSummary[]};
type GetResult={record:SourceChangeRecord};
type DecideResult={record:SourceChangeSummary;draft:Draft|null};

test('source review shows exact old/proposed text and acceptance creates an unpublished rebased draft',async()=>{
 const model=await import('../lib/authoring-model.ts');const editable=model.editableFromBaseline(BARECHU);assert.equal(editable.content.mode,'bilingual');const sourceId=editable.content.hebrewGroups[0].sourceId,current=model.sourcePack.sources.find(source=>source.id===sourceId)!;const prior=structuredClone(current) as AuthoringSource;const blockId=editable.content.hebrewGroups[0].blockIds[0],block=prior.blocks.find(item=>item.id===blockId)!;block.he=`${block.he!.slice(0,-1)}${block.he!.endsWith('א')?'ב':'א'}`;block.sourceBlockSha256=sha(JSON.stringify(block));prior.unitSha256=sha(JSON.stringify(prior.blocks));
 const now=Date.now(),draft:Draft={...editable,id:'changed-draft',version:1,sourcePin:model.sourcePinFor(editable.content,[prior],'0'.repeat(64)),sourceSnapshots:[prior],activeRevision:2,activeDraftVersion:1,createdAt:now,updatedAt:now,createdBy:'editor',updatedBy:'editor'};const drafts=new MemoryAuthoringRepository();await drafts.insertDraft(draft);const reviews=new MemorySourceReviewRepository(drafts),service=createSourceReviewService(drafts,reviews,async()=>[{id:'collection-1',name:'Kol Nidre service',service:'Yom Kippur',archived:false,matches:[{cueIds:['changed-draft']}]},{id:'collection-2',name:'Unrelated service',service:'Shabbat',archived:false,matches:[{cueIds:['another-cue']}]}]);
 const scan=await service.operation('scan',{},'reviewer') as ScanResult;assert.equal(scan.detected,1);assert.ok(scan.coverage.unopenedPublished.total>0);assert.equal(scan.coverage.unopenedPublished.total,scan.coverage.unopenedPublished.verifiable+scan.coverage.unopenedPublished.unverifiable);assert.ok(scan.coverage.unopenedPublished.message);assert.equal(scan.records[0].comparison,'exact');assert.equal(scan.records[0].affected.published,true);assert.deepEqual(scan.records[0].affected.serviceCollections.map(item=>item.name),['Kol Nidre service']);const detail=await service.operation('get',{id:scan.records[0].id},'reviewer') as GetResult;const changed=detail.record.changes.find(item=>item.channel==='he')!;assert.equal(changed.priorText,block.he);assert.equal(changed.proposedText,current.blocks.find(item=>item.id===blockId)!.he);assert.equal(changed.priorText!.length,changed.proposedText!.length);assert.equal(changed.role,'Hebrew');assert.equal(changed.paginationMayChange,true);
 const accepted=await service.operation('decide',{id:detail.record.id,expectedVersion:1,decision:'accept'},'reviewer') as DecideResult;assert.equal(accepted.record.status,'accepted');assert.equal(accepted.draft!.activeRevision,null);assert.equal(accepted.draft!.sourceSnapshots!.find(source=>source.id===sourceId)!.unitSha256,current.unitSha256);assert.equal(sourcePinFor(accepted.draft!.content,accepted.draft!.sourceSnapshots,accepted.draft!.sourcePin.feedSha256).unitSha256[sourceId],current.unitSha256);assert.equal((await drafts.getDraft('changed-draft'))!.activeRevision,2,'acceptance never changes the affected published draft');
});

test('removed sources remain visible as blocked review items',async()=>{
 const model=await import('../lib/authoring-model.ts');const editable=model.editableFromBaseline(BARECHU);assert.equal(editable.content.mode,'bilingual');const originalId=editable.content.hebrewGroups[0].sourceId,prior=structuredClone(model.sourcePack.sources.find(source=>source.id===originalId)!) as AuthoringSource;prior.id='removed-source';const replace=(groups:Array<{sourceId:string;blockIds:string[]}>)=>groups.map(group=>({...group,sourceId:'removed-source'}));const content={...editable.content,hebrewGroups:replace(editable.content.hebrewGroups),transliterationGroups:replace(editable.content.transliterationGroups)};const now=Date.now(),draft:Draft={...editable,content,id:'removed-draft',version:1,sourcePin:model.sourcePinFor(content,[prior],'0'.repeat(64)),sourceSnapshots:[prior],activeRevision:null,activeDraftVersion:null,createdAt:now,updatedAt:now,createdBy:'old',updatedBy:'old'};const drafts=new MemoryAuthoringRepository();await drafts.insertDraft(draft);const service=createSourceReviewService(drafts,new MemorySourceReviewRepository(drafts));const scan=await service.operation('scan',{},'reviewer') as ScanResult;assert.equal(scan.detected,1);assert.equal(scan.records[0].toUnitSha256,'missing');assert.match(scan.records[0].blockedReason!,/no longer available/);await assert.rejects(service.operation('decide',{id:scan.records[0].id,expectedVersion:1,decision:'accept'},'reviewer'),(error)=>(error as {code:string}).code==='source_update_blocked');
});

test('accept rejects a review when the affected draft changed after scanning',async()=>{
 const model=await import('../lib/authoring-model.ts');const editable=model.editableFromBaseline(BARECHU);assert.equal(editable.content.mode,'bilingual');const bilingual=editable.content as Extract<DraftContent,{mode:'bilingual'}>;const sourceId=bilingual.hebrewGroups[0].sourceId,current=model.sourcePack.sources.find(source=>source.id===sourceId)!,prior=structuredClone(current) as AuthoringSource,block=prior.blocks.find(item=>item.id===bilingual.hebrewGroups[0].blockIds[0])!;block.he=`${block.he} old`;block.sourceBlockSha256=sha(JSON.stringify(block));prior.unitSha256=sha(JSON.stringify(prior.blocks));const now=Date.now(),draft:Draft={...editable,id:'stale-draft',version:1,sourcePin:model.sourcePinFor(editable.content,[prior],'0'.repeat(64)),sourceSnapshots:[prior],activeRevision:null,activeDraftVersion:null,createdAt:now,updatedAt:now,createdBy:'old',updatedBy:'old'};const drafts=new MemoryAuthoringRepository();await drafts.insertDraft(draft);const service=createSourceReviewService(drafts,new MemorySourceReviewRepository(drafts));const scan=await service.operation('scan',{},'reviewer') as ScanResult;await drafts.updateDraft(draft.id,1,{...editable,title:'Changed after scan'},'other-editor');await assert.rejects(service.operation('decide',{id:scan.records[0].id,expectedVersion:1,decision:'accept'},'reviewer'),(error)=>(error as {code:string}).code==='stale_source_review');assert.equal((await drafts.listDrafts()).length,1);
});

test('historical drafts without snapshots are flagged unknown and cannot be accepted',async()=>{
 const model=await import('../lib/authoring-model.ts');const editable=model.editableFromBaseline(BARECHU),now=Date.now();const pin=model.sourcePinFor(editable.content);const sourceId=Object.keys(pin.unitSha256)[0];pin.unitSha256[sourceId]='f'.repeat(64);const draft:Draft={...editable,id:'historical',version:1,sourcePin:pin,activeRevision:null,activeDraftVersion:null,createdAt:now,updatedAt:now,createdBy:'old',updatedBy:'old'};const drafts=new MemoryAuthoringRepository();await drafts.insertDraft(draft);const service=createSourceReviewService(drafts,new MemorySourceReviewRepository(drafts));const scan=await service.operation('scan',{},'reviewer') as ScanResult;assert.equal(scan.records[0].comparison,'unavailable');assert.match(scan.records[0].blockedReason!,/historical source snapshot/);await assert.rejects(service.operation('decide',{id:scan.records[0].id,expectedVersion:1,decision:'accept'},'reviewer'),(error)=>(error as {code:string}).code==='source_update_blocked');
});

test('defer and reject require retained reasons and never create drafts',async()=>{
 const model=await import('../lib/authoring-model.ts');const editable=model.editableFromBaseline(BARECHU),now=Date.now();const pin=model.sourcePinFor(editable.content);const sourceId=Object.keys(pin.unitSha256)[0];pin.unitSha256[sourceId]='e'.repeat(64);const draft:Draft={...editable,id:'decision-draft',version:1,sourcePin:pin,activeRevision:null,activeDraftVersion:null,createdAt:now,updatedAt:now,createdBy:'old',updatedBy:'old'};const drafts=new MemoryAuthoringRepository();await drafts.insertDraft(draft);const service=createSourceReviewService(drafts,new MemorySourceReviewRepository(drafts));const scan=await service.operation('scan',{},'reviewer') as ScanResult;await assert.rejects(service.operation('decide',{id:scan.records[0].id,expectedVersion:1,decision:'defer'},'reviewer'),(error)=>(error as {code:string}).code==='reason_required');const deferred=await service.operation('decide',{id:scan.records[0].id,expectedVersion:1,decision:'defer',reason:'Confirm wording with clergy'},'reviewer') as DecideResult;assert.equal(deferred.record.status,'deferred');assert.equal(deferred.record.decision!.reason,'Confirm wording with clergy');const rejected=await service.operation('decide',{id:scan.records[0].id,expectedVersion:2,decision:'reject',reason:'Local source does not use this revision'},'reviewer') as DecideResult;assert.equal(rejected.record.status,'rejected');assert.equal((await drafts.listDrafts()).length,1);
});
