import {z} from 'zod/v4';
import {type RegisterTool,applyDefaults,draftFields,id,layoutId,rowOrder,templateCueId,textSize,version} from './shared';
import {hygieneToolSchemas} from '../catalog-hygiene-schemas';
import {draftReferenceSchema} from '../companion-deck/singular-references';
import {batchCreateDraftsSchema} from '../batch-drafts-schema';

const sharedHash=z.string().regex(/^[a-f0-9]{64}$/,{message:'Pass the 64-character cueHash list_shared_library or a dry run returned.'});

// Drafts from creation to publish, their sets, wording changes, revisions and rollback.
export function registerAuthoringTools(register:RegisterTool){
 register('list_drafts','List authoring drafts as bounded summaries, sorted by name and then set order: each row has its set (id, index, count), published, dirty (the draft has changes the live graphic lacks), archived, and an excerpt of what it reads. Filter by query, service, book or layout; page with limit and the nextCursor it returns; includeArchived adds archived drafts. compact:false returns every full record instead (large; no filters).',z.object({compact:z.boolean().default(true),query:z.string().min(1).max(100).optional(),service:z.string().min(1).max(100).optional(),book:z.string().min(1).max(100).optional(),layout:layoutId().optional(),limit:z.number().int().min(1).max(50).optional(),cursor:z.string().min(1).max(200).optional(),includeArchived:z.boolean().optional()}).strict(),{readOnlyHint:true});
 register('list_archived_drafts','List recoverable archived authoring drafts.',z.object({}).strict(),{readOnlyHint:true});
 register('get_draft',"Get one draft and its current version. view:'rendered' returns what the graphic reads on screen (texts, rows, validation) with its version, set and publish state, and none of the source snapshots; the default view:'full' is the complete record.",z.object({draftId:id,view:z.enum(['full','rendered']).optional()}).strict(),{readOnlyHint:true});
 register('list_wording_changes','List every edited siddur line in this workspace (local-variant wording): the draft, whether it is published or archived, the source and passage, the channel, the exact source text and the edited text, and why. Read only; use it to find source spellings to correct. It never changes a draft or the siddur.',z.object({}).strict(),{readOnlyHint:true});
 register('import_cue','Idempotently create or return a source-reference draft for an existing baseline cue. No plaintext prayer content is accepted.',z.object({cueId:id}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('create_draft','Create a source-reference draft with a new stable ID from search_sources block ids (includeBlocks:true), or content mode custom for free text. templateCueId is optional: left out, the layout\'s default look is used. textSize names a text size. The corner layout is a small card for a line or two in the bottom-right corner; it takes a lower-third (bottom) template.',draftFields().extend({textSize:textSize.optional(),applyDefaults:applyDefaults.optional(),reference:draftReferenceSchema.optional().describe('T3: what the old deck showed, as a convert_singular_deck row carries it. Kept with the draft for review (a review board shows it beside the graphic); never shown on screen.')}),{readOnlyHint:false});
 register('duplicate_draft','Copy one draft (draftId) or catalog graphic (cueId) into a new unpublished standalone draft, named "Copy of ..." unless name is given. expectedVersion, with draftId, refuses the copy if the draft changed since you read it.',z.object({draftId:id.optional(),cueId:id.optional(),name:z.string().min(1).max(80).optional(),expectedVersion:version.min(1).optional()}).strict(),{readOnlyHint:false});
 register('compose_custom_draft','Create an unpublished custom-text draft from one list_custom_templates form: values maps its field keys to text. layout defaults to the form\'s own; templateCueId to that layout\'s look.',z.object({templateId:z.enum(['speaker','announcement','citation','service-begins','corner']),values:z.record(z.string().min(1).max(40),z.string().max(300)),layout:layoutId().optional(),name:z.string().min(1).max(80).optional(),templateCueId:templateCueId.optional(),textSize:textSize.optional()}).strict(),{readOnlyHint:false});
 register('create_local_variant','Create an unpublished local liturgical variant while retaining exact source text and pins.',z.object({draftId:id.optional(),cueId:id.optional(),label:z.string().min(1).max(80),reason:z.string().min(1).max(500).optional(),overrides:z.array(z.object({sourceId:z.string().min(1).max(160),blockId:z.string().min(1).max(220),channel:z.enum(['he','tr','en']),localText:z.string().min(1).max(4000)}).strict()).min(1).max(96)}).strict(),{readOnlyHint:false});
 register('archive_draft','Archive a standalone draft without changing its published output.',z.object({draftId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('restore_draft','Restore a standalone archived draft.',z.object({draftId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 // MCP plan A3 - retire is the real retraction; archive only tidies the editor.
 register('retire_cue','Withdraw a published graphic from the live library: it leaves the catalog, Companion\'s picker and the relay, and services flag entries that use it. The draft and its revisions are kept, and the editor lists it as retired. A graphic on screen when you retire it stays there until someone takes it out, and it cannot be shown again until restore_cue. Not the same as archive_draft, which leaves the published graphic playing. cueId is the graphic\'s id (the draft id); a built-in graphic must be imported with import_cue first.',z.object({cueId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('restore_cue','Bring a retired graphic back into the live library at the same revision it had when it was retired, with no new review. Publishing or rolling back a retired draft also brings it back.',z.object({cueId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('archive_draft_set','Atomically archive a complete multipart draft set without changing published output.',z.object({setId:id,expectedDraftIds:z.array(id).min(1).max(200)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('restore_draft_set','Atomically restore a complete multipart draft set.',z.object({setId:id,expectedDraftIds:z.array(id).min(1).max(200)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('reorder_draft_set','Atomically reorder every slide in a multipart draft set.',z.object({setId:id,expectedDraftIds:z.array(id).min(1).max(200),orderedDraftIds:z.array(id).min(1).max(200)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('duplicate_draft_in_set','Duplicate one multipart slide with a new identity and contiguous set order.',z.object({draftId:id,expectedVersion:version.min(1),expectedDraftIds:z.array(id).min(1).max(200)}).strict(),{readOnlyHint:false});
 register('create_source_draft_set','Create an unpublished ordered set from every automatic block in one maintained source. templateCueId is optional: left out, the layout\'s default look is used.',z.object({sourceId:id,mode:z.enum(['bilingual','original-en','source-en']),includeTranslation:z.boolean().optional(),layout:layoutId(),templateCueId:id.optional(),applyDefaults:applyDefaults.optional()}).strict(),{readOnlyHint:false});
 register('review_draft_set','Verify exact-once source blocks, language channels, and order for a multipart draft set.',z.object({setId:id}).strict(),{readOnlyHint:true});
 register('split_draft_into_set','Split one existing source-backed draft at its current selected pinned blocks, preserving its presentation and source variants in an ordered unpublished set.',z.object({draftId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('update_draft','Update a draft using optimistic version matching. textSize sets a named text size on the presentation the patch leaves in place.',z.object({draftId:id,expectedVersion:version.min(1),patch:draftFields().partial().strict(),refreshSourceIds:z.array(id).min(1).max(24).optional(),textSize:textSize.optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('style_draft','Plan a readable draft style by default: comfortable typography and bilingual blocks. Dry run is the default; applying uses the same optimistic draft update safeguards and never publishes.',z.object({draftId:id,expectedVersion:version.min(1),layout:layoutId().optional(),arrangement:z.enum(['together','blocks']).optional(),rowOrder:rowOrder.optional(),comfortableTypography:z.boolean().optional(),latinLineBreaks:z.enum(['preserve','paragraphs','phrases']).optional(),dryRun:z.boolean().optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('preview_content','Show what content would look like on screen before any draft exists: the same fields as create_draft, nothing stored. includePreviewImage:true measures it in the server browser and returns the frame as an image; that verdict is not stored and cannot stand in for review_draft.',draftFields().extend({textSize:textSize.optional(),includePreviewImage:z.boolean().optional()}),{readOnlyHint:true});
 register('preview_draft','Create a version-bound preview and return its authenticated preview path and fit contract. A human must review it in the web UI before publishing.',z.object({draftId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('fit_check_draft','Measure a version-bound preview in a real browser on the server and store the result on that preview. includePreviewImage:true returns the frame as an image and keeps it with the preview, so the publications page can show what was checked. Returns pass, fail with the fit problems found, or unavailable with a web fit-check link.',z.object({draftId:id,expectedVersion:version.min(1),previewId:id,includePreviewImage:z.boolean().optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 // D18 - the MCP half of the review. An MCP actor's review carries no measurement of its own:
 // `review_draft` routes an `mcp:` actor to `attestedMeasurement`, which reads the
 // `server-chromium/` fit check stored on this exact preview and ignores anything asserted, so
 // there is nothing here a client could forge - which is why the schema has no
 // `browserMeasurement` field at all. Without this tool the attested path D18 built is
 // unreachable over MCP and `publish_draft` can never be satisfied: every MCP publish answers
 // 409 `review_required` however green the fit check is.
 register('review_draft','Approve a preview this actor has already fit-checked on the server. The receipt records approvedBy agent and the member who connected you; the measurement is the stored server fit check, and none can be supplied. humanApproved is optional and accepted for older clients.',z.object({draftId:id,expectedVersion:version.min(1),previewId:id,humanApproved:z.literal(true).optional()}).strict(),{readOnlyHint:false});
 register('publish_draft','Publish only a preview with a stored, exact-version review receipt. When another published graphic already has this name the publish is refused with a suggested name; confirmDuplicateName:true publishes under that suggestion instead.',z.object({draftId:id,expectedVersion:version.min(1),previewId:id,confirmDuplicateName:z.boolean().optional()}).strict(),{readOnlyHint:false});
 // R-A1 - the four calls above in one. It runs the same operations in order and stops, having
 // published nothing, where a person would have to decide something.
 register('ship_draft','Publish a draft in one call: preview, server fit check with the frame returned as an image, approval on that check, and publish. Returns shipped:true with the image, verdict, revision and final name. Otherwise shipped:false and stoppedAt says why, with nothing published: duplicate_name (pass allowRename:true to publish under suggestedName), validation, fit_failed (the renderer\'s own sentences and the image) or fit_unavailable (open the fit-check link). Publishes to the catalog; puts nothing on screen.',z.object({draftId:id,expectedVersion:version.min(1),allowRename:z.boolean().optional()}).strict(),{readOnlyHint:false});
 register('list_recent_publications','List graphics published since a time (milliseconds since 1970; default the last 7 days), newest first: name, when, whether an agent or a person published and approved it, the member, whether it is still the live version, whether its checked frame was kept, and rollbackTo - the revision rollback_draft would restore. actor narrows to agent or person publications. Read only.',z.object({since:z.number().int().nonnegative().optional(),actor:z.enum(['agent','person']).optional(),limit:z.number().int().min(1).max(200).optional()}).strict(),{readOnlyHint:true});
 register('list_slots','List the weekly slots (names and readings typed before a service) - or one service type\'s - with each slot\'s graphic, current text and draft version. Read only.',z.object({serviceType:z.string().min(1).max(80).optional()}).strict(),{readOnlyHint:true});
 register('save_slots','Save slot text for one service type in one call, as the web "This service" page does: every changed slot is republished under its standing approval, unchanged ones are left alone, and one overlong value refuses the whole Save. expectedVersions (slot key to the version list_slots returned) refuses the Save if a slot changed since you read it. Publishes to the catalog; puts nothing on screen.',z.object({serviceType:z.string().min(1).max(80),values:z.record(z.string().min(1).max(80),z.string().max(4000)),expectedVersions:z.record(z.string().min(1).max(80),version.min(1)).optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('list_revisions','List immutable revisions for a draft.',z.object({draftId:id}).strict(),{readOnlyHint:true});
 register('rollback_draft','Select an earlier immutable revision for future resolution.',z.object({draftId:id,expectedVersion:version.min(1),revision:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true,destructiveHint:true});
 // T1 - house defaults and the batch copy from the shared library (lib/authoring-defaults.ts, lib/shared-batch.ts).
 register('get_authoring_defaults','Read this workspace\'s house defaults - text size or font sizes, line spacing, Latin line breaks, panel row order, translation choice, arrangement and the layout rule - with the version update_authoring_defaults needs (0 when none are set) and the tools they apply on. Read only.',z.object({}).strict(),{readOnlyHint:true});
 register('update_authoring_defaults','Set this workspace\'s house defaults. New graphics (create_draft, compose_custom_draft, create_source_draft_set) and shared-library copies (customize_shared_cue, customize_shared_set, customize_shared_batch) take them unless the call names its own value or passes applyDefaults:false; existing drafts never change. A field replaces the stored one, null clears it, a field left out stays. textSize is a named size; fontSizes are explicit sizes and win over it. translation include adds the English translation where the source has it, omit leaves it out. layoutRule {maxLowerThirds:2, sequenceLayout:\'left\'} is the house rule that text needing more than two lower thirds becomes a left panel sequence (applied by create_source_draft_set; a copied set keeps its own shape and is flagged). expectedVersion is the version get_authoring_defaults returned.',z.object({expectedVersion:version,textSize:textSize.nullable().optional(),fontSizes:z.object({hebrewFontSize:z.number().int().min(24).max(52).optional(),transliterationFontSize:z.number().int().min(20).max(48).optional(),titleFontSize:z.number().int().min(20).max(42).optional()}).strict().nullable().optional(),lineSpacing:z.enum(['compact','spacious']).nullable().optional(),latinLineBreaks:z.enum(['preserve','paragraphs','phrases']).nullable().optional(),rowOrder:rowOrder.nullable().optional(),translation:z.enum(['include','omit']).nullable().optional(),arrangement:z.enum(['together','blocks']).nullable().optional(),layoutRule:z.object({maxLowerThirds:z.number().int().min(1).max(20),sequenceLayout:z.enum(['left','right']).default('left')}).strict().nullable().optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('customize_shared_batch','Copy up to 50 shared-library graphics into this workspace as unpublished drafts in one call, each as customize_shared_cue (cueId) or customize_shared_set (setId) would: attribution, source pins and the upstream link are kept, and the house defaults apply unless applyDefaults is false (per call or per item). dryRun is the default: it copies nothing and returns, per item, would-create, already-copied or refused with the reason, plus an apply list (items with their cue hashes) to send back with dryRun:false. Each item is its own copy, so one refusal never stops the rest. Resumable: an item already copied from the same upstream version is skipped, so running the same call again finishes what an interrupted one started. Publishes nothing.',z.object({items:z.array(z.object({cueId:id.optional(),setId:id.optional(),expectedCueHash:sharedHash.optional(),expectedCueHashes:z.record(z.string().min(1).max(160),sharedHash).optional(),name:z.string().min(1).max(80).optional(),applyDefaults:z.boolean().optional()}).strict()).min(1).max(500),applyDefaults:z.boolean().optional(),dryRun:z.boolean().default(true)}).strict(),{readOnlyHint:false,idempotentHint:true});
 // G4 - a build plan's drafts in one call, each through create_draft or customize_shared_batch (lib/batch-drafts.ts).
 register('batch_create_drafts','Make up to 50 unpublished drafts from a build plan in one call. Each item has your own stable key and a type: source (sourceId or sourceKey, with blockIds or a local source\'s block positions as blocks), set (the same source, with panels [{blockIds} or {blocks}], one graphic per panel, stored as one ordered set), slide (custom text, with an optional imageAssetId beside it) or customize_shared (cueId or setId from list_shared_library). Each is made as create_draft or customize_shared_batch would make it, house defaults included unless applyDefaults is false. Idempotent by key: a key that already made a live draft or set answers exists with its ids, and nothing is made. Dry run by default: every item is checked and nothing is written. Per-item results say created, exists, would-create or refused with the reason; one refusal never stops the rest. The result carries batchShip, the batch_ship input naming every draft made or found. Publishes nothing.',batchCreateDraftsSchema(),{readOnlyHint:false,idempotentHint:true});
 // A5 (R-H1-H3) - catalog hygiene. Every change is one of the single tools above, run per item.
 const hygiene=hygieneToolSchemas();
 register('find_catalog_issues','Find what is wrong with the library, read only: graphics that read the same on screen (duplicate_content), share a name or are copies of one (duplicate_name, near_duplicate_name, e.g. "Copy of Thank you"), carry a title copied from another graphic (inherited_title), are archived but still published (archived_but_published), are retired but still used by a service or a deck key (retired_in_service, retired_on_deck), came back under a name published since (restored_name_clash), or have changes not yet published (unpublished_changes). Each issue names the graphics (id, name, version), says what is wrong in a sentence, and names the tool that fixes it. kinds narrows the search.',hygiene.find_catalog_issues,{readOnlyHint:true});
 register('batch_update','Rename (name, title, accentTitle), restyle (the style_draft options) or archive many drafts in one call, each item with its own expectedVersion. Dry run by default: says what each item would do and changes nothing. With dryRun:false it runs update_draft, style_draft or archive_draft per item, one after another; a failed item is reported and the rest still run. Never publishes; a renamed published graphic keeps its old wording on screen until it is shipped again.',hygiene.batch_update,{readOnlyHint:false});
 register('batch_ship','Publish many drafts: one ship_draft per item (server fit check, approval, publish), each item with its own expectedVersion. Dry run by default: checks each item (version, validation, name clash) without opening a browser. With dryRun:false it ships items until about 40 seconds have passed, then returns nextCursor: call again with the same items and that cursor to continue. Per-item results say shipped, stopped (stoppedAt and why, nothing published), failed, or already_published (skipped, so repeating a call is safe). Frames are not returned; use ship_draft for one graphic with its image. Publishes to the catalog; puts nothing on screen.',hygiene.batch_ship,{readOnlyHint:false});
 register('batch_retire','Retire up to 200 published graphics in one call: each item is one retire_cue (the graphic leaves the live library, Companion\'s picker and the relay catalog, and its name is free for the next ship), with its own expectedVersion. Dry run by default: says, per item, would-retire, already-retired or refused with retire_cue\'s own reason, and changes nothing. With dryRun:false each item runs retire_cue in turn; a refused item is reported and the rest still run. A part of a multipart set retires alone, as with retire_cue, and the item warns when other published parts are not in the call. Archived-but-published graphics come ready as items in find_catalog_issues\' batchRetire. restore_cue brings one back.',hygiene.batch_retire,{readOnlyHint:false,destructiveHint:true,idempotentHint:true});
 register('supersede_cue','Replace one published graphic with another everywhere it is used: every prepared service entry, coverage decision and candidate, and every Companion deck key bound to old move to new, then old is retired (retire_cue; expectedVersion is the old graphic\'s draft version). Dry run by default: lists every service row and deck key that would move. Row and key labels are left as they are. new must already be published.',hygiene.supersede_cue,{readOnlyHint:false,destructiveHint:true});
}
