import {z} from 'zod/v4';
import {type RegisterTool,draftFields,id,layoutId,rowOrder,templateCueId,textSize,version} from './shared';

// Drafts from creation to publish, their sets, wording changes, revisions and rollback.
export function registerAuthoringTools(register:RegisterTool){
 register('list_drafts','List authoring drafts as bounded summaries, sorted by name and then set order: each row has its set (id, index, count), published, dirty (the draft has changes the live graphic lacks), archived, and an excerpt of what it reads. Filter by query, service, book or layout; page with limit and the nextCursor it returns; includeArchived adds archived drafts. compact:false returns every full record instead (large; no filters).',z.object({compact:z.boolean().default(true),query:z.string().min(1).max(100).optional(),service:z.string().min(1).max(100).optional(),book:z.string().min(1).max(100).optional(),layout:layoutId().optional(),limit:z.number().int().min(1).max(50).optional(),cursor:z.string().min(1).max(200).optional(),includeArchived:z.boolean().optional()}).strict(),{readOnlyHint:true});
 register('list_archived_drafts','List recoverable archived authoring drafts.',z.object({}).strict(),{readOnlyHint:true});
 register('get_draft',"Get one draft and its current version. view:'rendered' returns what the graphic reads on screen (texts, rows, validation) with its version, set and publish state, and none of the source snapshots; the default view:'full' is the complete record.",z.object({draftId:id,view:z.enum(['full','rendered']).optional()}).strict(),{readOnlyHint:true});
 register('list_wording_changes','List every edited siddur line in this workspace (local-variant wording): the draft, whether it is published or archived, the source and passage, the channel, the exact source text and the edited text, and why. Read only; use it to find source spellings to correct. It never changes a draft or the siddur.',z.object({}).strict(),{readOnlyHint:true});
 register('import_cue','Idempotently create or return a source-reference draft for an existing baseline cue. No plaintext prayer content is accepted.',z.object({cueId:id}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('create_draft','Create a source-reference draft with a new stable ID from search_sources block ids (includeBlocks:true), or content mode custom for free text. templateCueId is optional: left out, the layout\'s default look is used. textSize names a text size. The corner layout is a small card for a line or two in the bottom-right corner; it takes a lower-third (bottom) template.',draftFields().extend({textSize:textSize.optional()}),{readOnlyHint:false});
 register('duplicate_draft','Copy one draft (draftId) or catalog graphic (cueId) into a new unpublished standalone draft, named "Copy of ..." unless name is given. expectedVersion, with draftId, refuses the copy if the draft changed since you read it.',z.object({draftId:id.optional(),cueId:id.optional(),name:z.string().min(1).max(80).optional(),expectedVersion:version.min(1).optional()}).strict(),{readOnlyHint:false});
 register('compose_custom_draft','Create an unpublished custom-text draft from one list_custom_templates form: values maps its field keys to text. layout defaults to the form\'s own; templateCueId to that layout\'s look.',z.object({templateId:z.enum(['speaker','announcement','citation','service-begins','corner']),values:z.record(z.string().min(1).max(40),z.string().max(300)),layout:layoutId().optional(),name:z.string().min(1).max(80).optional(),templateCueId:templateCueId.optional(),textSize:textSize.optional()}).strict(),{readOnlyHint:false});
 register('create_local_variant','Create an unpublished local liturgical variant while retaining exact source text and pins.',z.object({draftId:id.optional(),cueId:id.optional(),label:z.string().min(1).max(80),reason:z.string().min(1).max(500).optional(),overrides:z.array(z.object({sourceId:z.string().min(1).max(160),blockId:z.string().min(1).max(220),channel:z.enum(['he','tr','en']),localText:z.string().min(1).max(4000)}).strict()).min(1).max(96)}).strict(),{readOnlyHint:false});
 register('archive_draft','Archive a standalone draft without changing its published output.',z.object({draftId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('restore_draft','Restore a standalone archived draft.',z.object({draftId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 // MCP plan A3 - retire is the real retraction; archive only tidies the editor.
 register('retire_cue','Withdraw a published graphic from the live library: it leaves the catalog, Companion\'s picker and the relay, and services flag entries that use it. The draft and its revisions are kept, and the editor lists it as retired. A graphic on screen when you retire it stays there until someone takes it out, and it cannot be shown again until restore_cue. Not the same as archive_draft, which leaves the published graphic playing. cueId is the graphic\'s id (the draft id); a built-in graphic must be imported with import_cue first.',z.object({cueId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('restore_cue','Bring a retired graphic back into the live library at the same revision it had when it was retired, with no new review. Publishing or rolling back a retired draft also brings it back.',z.object({cueId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('archive_draft_set','Atomically archive a complete multipart draft set without changing published output.',z.object({setId:id,expectedDraftIds:z.array(id).min(1).max(200)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('restore_draft_set','Atomically restore a complete multipart draft set.',z.object({setId:id,expectedDraftIds:z.array(id).min(1).max(200)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('reorder_draft_set','Atomically reorder every slide in a multipart draft set.',z.object({setId:id,expectedDraftIds:z.array(id).min(1).max(200),orderedDraftIds:z.array(id).min(1).max(200)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('duplicate_draft_in_set','Duplicate one multipart slide with a new identity and contiguous set order.',z.object({draftId:id,expectedVersion:version.min(1),expectedDraftIds:z.array(id).min(1).max(200)}).strict(),{readOnlyHint:false});
 register('create_source_draft_set','Create an unpublished ordered set from every automatic block in one maintained source. templateCueId is optional: left out, the layout\'s default look is used.',z.object({sourceId:id,mode:z.enum(['bilingual','original-en','source-en']),includeTranslation:z.boolean().optional(),layout:layoutId(),templateCueId:id.optional()}).strict(),{readOnlyHint:false});
 register('review_draft_set','Verify exact-once source blocks, language channels, and order for a multipart draft set.',z.object({setId:id}).strict(),{readOnlyHint:true});
 register('split_draft_into_set','Split one existing source-backed draft at its current selected pinned blocks, preserving its presentation and source variants in an ordered unpublished set.',z.object({draftId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('update_draft','Update a draft using optimistic version matching. textSize sets a named text size on the presentation the patch leaves in place.',z.object({draftId:id,expectedVersion:version.min(1),patch:draftFields().partial().strict(),refreshSourceIds:z.array(id).min(1).max(24).optional(),textSize:textSize.optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('style_draft','Plan a readable draft style by default: comfortable typography and bilingual blocks. Dry run is the default; applying uses the same optimistic draft update safeguards and never publishes.',z.object({draftId:id,expectedVersion:version.min(1),layout:layoutId().optional(),arrangement:z.enum(['together','blocks']).optional(),rowOrder:rowOrder.optional(),comfortableTypography:z.boolean().optional(),latinLineBreaks:z.enum(['preserve','paragraphs','phrases']).optional(),dryRun:z.boolean().optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('preview_content','Show what content would look like on screen before any draft exists: the same fields as create_draft, nothing stored. includePreviewImage:true measures it in the server browser and returns the frame as an image; that verdict is not stored and cannot stand in for review_draft.',draftFields().extend({textSize:textSize.optional(),includePreviewImage:z.boolean().optional()}),{readOnlyHint:true});
 register('preview_draft','Create a version-bound preview and return its authenticated preview path and fit contract. A human must review it in the web UI before publishing.',z.object({draftId:id,expectedVersion:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('fit_check_draft','Measure a version-bound preview in a real browser on the server and store the result on that preview. Optional preview image is ephemeral and is never stored. Returns pass, fail with the fit problems found, or unavailable with a web fit-check link.',z.object({draftId:id,expectedVersion:version.min(1),previewId:id,includePreviewImage:z.boolean().optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 // D18 - the MCP half of the review. An MCP actor's review carries no measurement of its own:
 // `review_draft` routes an `mcp:` actor to `attestedMeasurement`, which reads the
 // `server-chromium/` fit check stored on this exact preview and ignores anything asserted, so
 // there is nothing here a client could forge - which is why the schema has no
 // `browserMeasurement` field at all. Without this tool the attested path D18 built is
 // unreachable over MCP and `publish_draft` can never be satisfied: every MCP publish answers
 // 409 `review_required` however green the fit check is.
 register('review_draft','Record human approval for a preview this actor has already fit-checked on the server. The measurement is the stored server fit check; none can be supplied.',z.object({draftId:id,expectedVersion:version.min(1),previewId:id,humanApproved:z.literal(true)}).strict(),{readOnlyHint:false});
 register('publish_draft','Publish only a preview with a stored, exact-version human review receipt.',z.object({draftId:id,expectedVersion:version.min(1),previewId:id}).strict(),{readOnlyHint:false});
 register('list_slots','List the weekly slots (names and readings typed before a service) - or one service type\'s - with each slot\'s graphic, current text and draft version. Read only.',z.object({serviceType:z.string().min(1).max(80).optional()}).strict(),{readOnlyHint:true});
 register('save_slots','Save slot text for one service type in one call, as the web "This service" page does: every changed slot is republished under its standing approval, unchanged ones are left alone, and one overlong value refuses the whole Save. expectedVersions (slot key to the version list_slots returned) refuses the Save if a slot changed since you read it. Publishes to the catalog; puts nothing on screen.',z.object({serviceType:z.string().min(1).max(80),values:z.record(z.string().min(1).max(80),z.string().max(4000)),expectedVersions:z.record(z.string().min(1).max(80),version.min(1)).optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('list_revisions','List immutable revisions for a draft.',z.object({draftId:id}).strict(),{readOnlyHint:true});
 register('rollback_draft','Select an earlier immutable revision for future resolution.',z.object({draftId:id,expectedVersion:version.min(1),revision:version.min(1)}).strict(),{readOnlyHint:false,idempotentHint:true,destructiveHint:true});
}
