import {z} from 'zod/v4';
import {BRANDING_COLOR_KEYS,BRANDING_COLOR_ROLES,BRANDING_FONT_ROLES,BRANDING_FONT_ROLE_USES,brandingFontChoices} from '../branding-palette';
import {type McpIdentity,type RegisterTool,version} from './shared';

// Workspace branding as data (packet L4, R-B2). Operations live in lib/branding-tools.ts.
const hex=z.string().regex(/^#[0-9a-fA-F]{6}$/,{message:'Pass a six-digit hex colour such as #d9a62e, or null to go back to the built-in value.'});
const assetId=z.string().regex(/^asset_[a-f0-9]{64}$/,{message:'Pass an asset id from list_assets (asset_ followed by 64 hex characters), or null to go back to the built-in artwork.'});
const colors=()=>z.object(Object.fromEntries(BRANDING_COLOR_KEYS.map(key=>[key,hex.nullable().optional().describe(`Paints ${BRANDING_COLOR_ROLES[key]}.`)]))).strict().describe('Only the colours to change; null puts one back to the built-in value.');
// Every installed overlay face is offered here; a book face is refused by the operation unless the workspace has book faces on.
const fonts=()=>{const family=z.enum(brandingFontChoices(true) as [string,...string[]]);return z.object(Object.fromEntries(BRANDING_FONT_ROLES.map(role=>[role,family.nullable().optional().describe(`The face for ${BRANDING_FONT_ROLE_USES[role]}.`)]))).strict().describe('Font roles, chosen from the installed overlay fonts (get_branding lists the ones this workspace can use); null goes back to the built-in face. A new font is a code change.')};
const artwork=z.object({logo:assetId.nullable().optional().describe('The medallion on every graphic that has no artwork of its own.'),restingLogo:assetId.nullable().optional().describe('The standing corner mark, for a workspace that has one.'),scanCard:assetId.nullable().optional().describe('Artwork kept for the scan card (not drawn yet).')}).strict().describe('Artwork by asset id from list_assets (upload_asset adds one); null goes back to the built-in artwork.');
const changes=()=>({colors:colors().optional(),fonts:fonts().optional(),artwork:artwork.optional()});

export function registerBrandingTools(register:RegisterTool,identity:McpIdentity){
 register('get_branding',`Read the ${identity.shortName} branding every graphic is drawn with: each colour (its value, the built-in value, whether it is set, and what it paints), the latin and hebrew font roles with the faces this workspace can use, and the logo, resting logo and scan card artwork. version is what update_branding takes as expectedVersion (0 when nothing is stored).`,z.object({}).strict(),{readOnlyHint:true});
 register('preview_branding',`Show a ${identity.shortName} branding change before saving it: the server browser draws one graphic per layout (bottom, left, right, corner), or up to four named with cueIds, with the change applied and returns the frames. Nothing is saved. With no changes it shows the saved branding.`,z.object({...changes(),cueIds:z.array(z.string().min(1).max(200)).min(1).max(4).optional().describe('Up to four graphic ids from list_catalog to draw instead of one per layout.')}).strict(),{readOnlyHint:true});
 register('update_branding',`Change the ${identity.shortName} branding: name only the colours, font roles or artwork that change (null puts one back). expectedVersion is the version get_branding returned. Artwork used here becomes public, like a published graphic's. New previews, the editor and the server fit use it at once; an output page already open keeps the old look until it is reloaded. Try it with preview_branding first.`,z.object({expectedVersion:version,...changes()}).strict(),{readOnlyHint:false});
}
