import {z} from 'zod/v4';
import {type McpIdentity,type RegisterTool,applyDefaults,id,layoutId,version} from './shared';

const hash=z.string().regex(/^[a-f0-9]{64}$/,{message:'Pass the 64-character cueHash list_shared_library returned.'});
const lookMode=z.enum(['bilingual','source-en','original-en','local-variant','custom']);

// Which congregation this is, and what can be authored from: the source corpus, the baseline
// templates and looks, the published catalog, CRC's shared library and the source-change inbox.
export function registerCatalogTools(register:RegisterTool,identity:McpIdentity){
 register('get_workspace',`Say which congregation this connection serves (${identity.organizationName}, workspace '${identity.workspaceId}' at ${identity.host}) and whether it is a rehearsal. Call it first when you hold more than one overlays connector; every change here takes this workspace id.`,z.object({}).strict(),{readOnlyHint:true});
 register('search_sources',`Search the authorized ${identity.shortName} source corpus. Returns references, never a public corpus export. Compact by default: no licence or pin blocks. includeBlocks:true adds each block id with its kind and first words, which is everything create_draft needs (no get_source). book and service narrow to one siddur or service (list_source_facets names them); page narrows to units printed on that page. This workspace's own local sources (add_local_source) are searched too and are marked local. compact:false returns the full legacy summaries.`,z.object({query:z.string().min(1).max(100).optional(),book:z.string().min(1).max(100).optional(),service:z.string().min(1).max(100).optional(),page:z.number().int().min(1).max(9999).optional(),limit:z.number().int().min(1).max(50).optional(),includeBlocks:z.boolean().optional(),compact:z.boolean().default(true)}).strict(),{readOnlyHint:true});
 register('get_source','Get one authorized source by ID.',z.object({sourceId:id}).strict(),{readOnlyHint:true});
 register('list_source_facets','List the books (siddurim) and services the source corpus is organised by, with how many units each holds. Pass a value to search_sources book/service or to list_book_units.',z.object({}).strict(),{readOnlyHint:true});
 register('list_book_units','List one book as its printed outline: every unit by section, with its folio, block kinds and count. Names only, never the text; search_sources or get_source reads a unit.',z.object({book:z.string().min(1).max(100)}).strict(),{readOnlyHint:true});
 register('list_templates','List baseline cue templates and whether each can be imported, the default look for each layout (looks: the template create_draft uses when templateCueId is left out), and the named text sizes. mode changes only the look labels.',z.object({mode:lookMode.optional()}).strict(),{readOnlyHint:true});
 register('list_custom_templates','List the guided forms for graphics that come from no source: speaker, announcement, scripture citation, service start time and corner card, with each field and its length limit. compose_custom_draft fills one.',z.object({}).strict(),{readOnlyHint:true});
 register('list_catalog',`List every graphic in the ${identity.shortName} catalog - baseline and published - with its draft (if any), origin and what opening it would do (open, import or duplicate). list_drafts hides catalog graphics nobody has opened yet; this does not.`,z.object({query:z.string().min(1).max(100).optional(),layout:layoutId().optional()}).strict(),{readOnlyHint:true});
 // The shared library (CRC's export, as TBI's editor shelf reads it). Descriptions stay unnamed so a
 // TBI connection says nothing about CRC (tests/mcp.test.ts); on CRC itself it answers unavailable.
 register('list_shared_library','List the shared library - graphics the partner congregation shares with this one - and whether each is already here, changed since it was copied, or new. Read only.',z.object({query:z.string().min(1).max(100).optional(),limit:z.number().int().min(1).max(1000).optional(),refresh:z.boolean().optional()}).strict(),{readOnlyHint:true});
 register('preview_shared_cue','Show one shared-library graphic exactly as its congregation publishes it, with the cueHash customize_shared_cue needs. Copies its artwork into this workspace\'s asset library if it has any; creates no draft.',z.object({cueId:id,refresh:z.boolean().optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('customize_shared_cue','Copy one shared-library graphic into an unpublished draft here. expectedCueHash is the hash you previewed; if it changed upstream since, nothing is copied and you are asked to preview again.',z.object({cueId:id,expectedCueHash:hash,name:z.string().min(1).max(80).optional(),applyDefaults:applyDefaults.optional()}).strict(),{readOnlyHint:false});
 register('customize_shared_set','Copy a whole shared-library multipart prayer into one unpublished set here, all parts or none. expectedCueHashes maps every part\'s cue id to the hash you previewed.',z.object({setId:id,expectedCueHashes:z.record(z.string().min(1).max(160),hash),applyDefaults:applyDefaults.optional()}).strict(),{readOnlyHint:false});
 register('compare_shared_cue','Say what changed upstream in a shared-library graphic since this draft was copied from it: wording, layout and presentation, line by line. Read only.',z.object({cueId:id,draftId:id}).strict(),{readOnlyHint:true});
 // The source-change inbox (/api/source-review): upstream siddur edits that reach a graphic here.
 register('scan_source_changes','Compare every graphic here with the current source corpus and record, in the source-change inbox, each one whose source wording changed upstream. Publishes nothing and changes no draft.',z.object({}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('list_source_changes','List the source-change inbox: each upstream wording change that reaches a graphic here, and its status. Read only.',z.object({}).strict(),{readOnlyHint:true});
 register('get_source_change','Get one source change with the old and new source text side by side and the version decide_source_change needs.',z.object({id}).strict(),{readOnlyHint:true});
 register('decide_source_change','Decide one source change: accept makes an unpublished draft on the new wording (publish it the usual way); defer and reject need a reason. expectedVersion is the version get_source_change returned.',z.object({id,expectedVersion:version.min(1),decision:z.enum(['accept','defer','reject']),reason:z.string().min(1).max(500).optional()}).strict(),{readOnlyHint:false});
 // T2 - this workspace's own sources (lib/local-sources.ts): readings it enters itself, with book and page,
 // merged into what search_sources, get_source and list_book_units read. Never shared with another congregation.
 const pageRefusal='page must be the printed page number, a whole number from 1 to 9999.';
 const localKind=z.enum(['prayer-book reading','song setting','tbi text'],{error:"kind must be one of 'prayer-book reading', 'song setting', 'tbi text'."}).describe("What the source is: a 'prayer-book reading' (the default), a 'song setting' or a 'tbi text' (the congregation's own). A prayer-book reading from a named book needs its page; the others may have no book or page.");
 const localBlock=z.object({he:z.string().min(1).max(2000).optional(),tr:z.string().min(1).max(2000).optional(),en:z.string().min(1).max(2000).optional()}).strict().describe('One passage: he (Hebrew) with tr (its transliteration), optionally en (its English translation); tr alone, or tr with en, for a line sung in transliteration (it renders as a transliteration row, never an empty Hebrew one); or en alone for an English reading.');
 const localFields={name:z.string().min(1).max(120),kind:localKind,book:z.string().min(1).max(100).describe("The printed book, e.g. Mishkan T'filah. Leave it out for a source no book prints."),page:z.number({error:pageRefusal}).int({error:pageRefusal}).min(1,{error:pageRefusal}).max(9999,{error:pageRefusal}).describe('The printed page number. A page needs its book; a prayer-book reading from a named book needs its page.'),section:z.string().min(1).max(120),service:z.string().min(1).max(120),attribution:z.string().min(1).max(300).describe('Who wrote or holds the text, as it should be credited. Stored exactly as given; leave it out when there is no credit (never invent one): the source then says "not credited" and a graphic carries no credit line.'),licence:z.string().min(1).max(2000).describe('Licence or permission text, stored exactly as given; nothing is inferred.'),aliases:z.array(z.string().min(1).max(100)).max(12),blocks:z.array(localBlock).min(1).max(48)};
 register('add_local_source',`Enter a reading ${identity.shortName} owns (a prayer-book page, a song setting, its own text) once, as a source: its kind, blocks of he / tr / en, its attribution and licence text as given, and its printed position {book, page} when it has one. It is then found by search_sources (by text and kind, and by book and page when printed), read by get_source and listed by list_book_units when it has a book, and drafts built from it are source-backed like any other. It stays in this workspace and is never shared.`,z.object({name:localFields.name,kind:localFields.kind.optional(),book:localFields.book.optional(),page:localFields.page.optional(),section:localFields.section.optional(),service:localFields.service.optional(),attribution:localFields.attribution.optional(),licence:localFields.licence.optional(),aliases:localFields.aliases.optional(),blocks:localFields.blocks}).strict(),{readOnlyHint:false});
 register('update_local_source','Change a local source. expectedVersion is the version list_local_sources returned; fields left out stay as they are, blocks replaces every block, and null clears book, page, attribution, section, service or licence. A wording change moves the version, and drafts pinned to the earlier wording show as stale until refreshed (scan_source_changes, or update_draft refreshSourceIds).',z.object({sourceId:z.string().min(7).max(200).regex(/^local:/,{message:'Pass a local source id (local:...) from list_local_sources.'}),expectedVersion:version.min(1),name:localFields.name.optional(),kind:localFields.kind.optional(),book:localFields.book.nullable().optional(),page:localFields.page.nullable().optional(),section:localFields.section.nullable().optional(),service:localFields.service.nullable().optional(),attribution:localFields.attribution.nullable().optional(),licence:localFields.licence.nullable().optional(),aliases:localFields.aliases.optional(),blocks:localFields.blocks.optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
 register('list_local_sources',`List the sources ${identity.shortName} entered itself, by book and page (those with no book last): each with its kind, version, attribution ("not credited" when it has none), licence, block ids and the drafts that use it (stale when a draft pins an earlier wording). Filter by query, kind, book or page. Read only.`,z.object({query:z.string().min(1).max(100).optional(),kind:localKind.optional(),book:z.string().min(1).max(100).optional(),page:z.number().int().min(1).max(9999).optional(),limit:z.number().int().min(1).max(200).optional()}).strict(),{readOnlyHint:true});
 // G3 - many sources in one call, from a dropped file (open_import_dropzone kind 'local-sources') or inline.
 const importItem=z.record(z.string(),z.unknown()).describe('One build-prep item: key, name, kind, book, page, section, service, attribution, licence, aliases, blocks [{he, tr, en}]. null means not given. Any other field (title, layout, panels, notes, ...) is planning only: it is ignored and listed once in the result.');
 register('import_local_sources',`Enter many ${identity.shortName} sources at once, idempotently by each item's key: a new key creates a source, a key seen before updates the same source when anything changed and otherwise reports it unchanged. Pass importId (a 'local-sources' import from open_import_dropzone: a JSON array, or {items:[...]}) or up to 100 items inline as sources. One bad item never stops the rest; each item reports its status, local: id, version, the reason when refused, and blockSha256 (sha256 of each stored block's [he, tr, en] as stored) so you can prove the text arrived byte for byte. dryRun:true reports what would happen and writes nothing.`,z.object({importId:z.string().regex(/^import_[a-f0-9]{32}$/,{message:'Pass the importId open_import_dropzone returned (import_ followed by 32 hex characters).'}).optional(),sources:z.array(importItem).min(1).max(100).optional(),dryRun:z.boolean().optional()}).strict(),{readOnlyHint:false,idempotentHint:true});
}
