import {z} from 'zod/v4';
import {deckToolSchemas as s} from '../companion-deck/tool-schemas';
import {SINGULAR_EXTRACT,SINGULAR_EXTRACT_FLAT} from '../companion-deck/singular-references';
import {type McpIdentity,type RegisterTool,version} from './shared';

// The stored Companion deck (Track C): the whole Stream Deck configuration, kept as a complete, stable
// library. Every change takes the deck version you read, is validated before it is saved, and is
// refused (nothing saved) if it would break the deck. Nothing here reaches the booth: the deck reaches
// Companion only as the exported file a person imports.
export function registerDeckTools(register:RegisterTool,identity:McpIdentity){
 const who=identity.shortName;
 // C3 (R-C3, R-C4 full scope). Keep this block contiguous; C4 appends its registrations after it.
 register('get_deck',`Read the ${who} Companion deck in brief: its version, pages (number, name, template, how many keys and free cells), service chains, templates and connection labels. get_deck_page reads one page cell by cell.`,s.get_deck,{readOnlyHint:true});
 register('get_deck_page','Read one deck page cell by cell (rows and columns count from 0): each key\'s kind and label, the cue it fires with its role, sequence and camera gesture, the template\'s fixed keys, and the free cells.',s.get_deck_page,{readOnlyHint:true});
 register('create_page','Create a deck page on one of the deck\'s templates, with the template\'s fixed keys. chainAfter puts it into a service\'s Prev/Next chain; jumpFrom adds a key that jumps to it (a page nothing reaches is refused).',s.create_page,{readOnlyHint:false});
 register('rename_page','Rename a deck page, with the Prev/Next and hub keys that name it.',s.rename_page,{readOnlyHint:false,idempotentHint:true});
 register('move_page','Move a deck page to an unused page number; every key that jumps to it follows.',s.move_page,{readOnlyHint:false});
 register('delete_page','Delete a deck page. Refused while any key other than Prev/Next still jumps to it, and for Home.',s.delete_page,{readOnlyHint:false,destructiveHint:true});
 register('place_button','Place a key on an empty cell: a cue key (label and colour role default from the catalog), a page jump, an Overlays module action, a device key the deck carries, a camera merge, or a copy of another key. A device key placed twice gets new ids.',s.place_button,{readOnlyHint:false});
 register('move_button','Move a key to an empty cell, on the same page or another. It keeps its ids, cue, gesture and label.',s.move_button,{readOnlyHint:false});
 register('remove_button','Remove a key from the deck.',s.remove_button,{readOnlyHint:false,destructiveHint:true});
 register('bind_cue','Point a cue key at a cue (or make a new cue key on an empty cell). The key keeps its camera gesture and ids; the label follows the new cue unless you give one.',s.bind_cue,{readOnlyHint:false,idempotentHint:true});
 register('attach_camera_gesture','Give a cue key the camera gesture (show the cue, recall a PTZ preset, wait, merge; the second press takes it out and returns the camera), copy one from another key, or remove it with gesture:null. Only on pages whose template allows gestures.',s.attach_camera_gesture,{readOnlyHint:false,idempotentHint:true});
 register('apply_template','(Re)apply a page template: put back any missing fixed key (switcher, recovery, Prev/Home/Next, Bimah Mute) and make Prev/Next follow the chain. A key sitting on a reserved cell is refused unless replace:true.',s.apply_template,{readOnlyHint:false,idempotentHint:true});
 register('layout_column','Lay out one column\'s cue keys by the deck grammar: the lead at the top, a sequence\'s parts down in order, then alternates and short selections; or in the order you give. Colour follows each key\'s role.',s.layout_column,{readOnlyHint:false,idempotentHint:true});
 register('sync_deck_with_catalog',`Keep the ${who} deck in step with the catalog after publishing, revising or retiring graphics: places each new cue on its standing page by the deck grammar (a sequence continues down its column, an alternate joins its slot's column), relabels renamed cues, and removes or flags keys bound to retired cues. Cues the grammar cannot place are listed with the reason; pass placements to say where. Dry run by default.`,s.sync_deck_with_catalog,{readOnlyHint:false});
 register('check_service_on_deck','Say whether every graphic a prepared service needs is on the deck: where each placed one is, and for each missing one where the grammar would put it (or why it cannot). Reads only.',s.check_service_on_deck,{readOnlyHint:true});
 register('validate_deck',`Check the whole ${who} deck: page templates and chains, cue bindings against the published catalog (retired or unpublished cues fail), connection labels exactly as the booth must have them, the module's actions and feedbacks, and reachability. Findings name the page, row and column.`,s.validate_deck,{readOnlyHint:true});
 register('export_deck_config','Make the full Companion export of the deck for the next big import: validates first (refused with the errors if it fails), then returns a signed download link that works for 15 minutes, the file\'s sha256 and every connection label the booth must match exactly. The same download is on the Setup page for a signed-in member.',s.export_deck_config,{readOnlyHint:true,idempotentHint:true});
 // G6 (TBI redo) - a whole deck plan in one call.
 register('apply_deck_plan',`Lay a whole deck plan on the ${who} deck in one write: one row per button (page,row,col,label,bg,targetKind,targetKey,panelIndex,notes), given as rows or as the importId of a deck-plan import (CSV or a JSON array). A graphic row (local, corpus, slide, crc) binds its cell to the published cue its build key became (a draft key, or a draft-set key with panelIndex picking the part; targets overrides), with the plan's label and #rrggbb colour and the Requested and Rendered lights. Camera (birddog) and OBS keys, Companion's built-in navigation and template keys are kept exactly as they are, and a device key that is not where the plan says is reported. empty clears a graphic key from its cell; dropped is not placed. Any graphic whose key is unbuilt or unpublished refuses the whole apply. Dry run by default: the full change plan, every finding and validate_deck's findings on the would-be deck; with dryRun:false and expectedVersion it is saved once, validated like every deck change.`,s.apply_deck_plan,{readOnlyHint:false});
 // C4 (R-C7, R-C9) - a deck seeded from a Companion export, and its Singular buttons converted to published graphics.
 const rowId=z.string().regex(/^\d{1,2}\/\d\/\d$/,{message:'A row id is "page/row/column" as convert_singular_deck returns it, for example "3/0/5".'});
 register('seed_deck_from_export',`Seed the ${identity.shortName} Companion deck from a Companion 5 full export: every page, position, label and colour is kept, Companion's own page up / number / down buttons stay, camera and OBS buttons are carried as they are, and each Singular.live graphic button becomes a placeholder that convert_singular_deck can bind. Every connection's settings and passwords are discarded on the server before anything is kept, and the uploaded file itself is never stored. Pass export (the .companionconfig file, base64) or useCommittedSeed:true for Simone's 14 September deck. Dry run by default; replacing a stored deck needs its expectedVersion. Only TBI's deck is seeded this way; a deck built from a released preset is changed with the deck tools instead.`,z.object({export:z.string().min(16).max(1_000_000).optional().describe('The .companionconfig file exactly as Companion exported it (gzip or JSON), base64-encoded. It is read in memory and dropped; only the derived deck is kept.'),fileName:z.string().min(1).max(160).optional(),useCommittedSeed:z.boolean().optional().describe("Use Simone's deck as exported on 14 September 2026 (already derived, no upload needed)."),expectedVersion:version.min(1).optional().describe('The stored deck version you read, required to replace a stored deck.'),dryRun:z.boolean().default(true)}).strict(),{readOnlyHint:false,destructiveHint:true});
 register('convert_singular_deck',`Match every Singular.live button on the stored ${identity.shortName} deck to a published graphic, by the same forgiving title search prepare_service_from_setlist uses. Each button comes back Covered (one clear match), Needs review (several candidates, or a defect to settle) or Needs a graphic, with defects named: two presses firing different graphics, a label naming a different prayer than it fires, two buttons with one label on a page, working notes in a label. Dry run by default. With dryRun:false, expectedVersion and bind (row ids from the dry run), only Covered rows are bound, each becoming a one-press key with the Requested and Rendered lights; anything else named is refused and nothing changes. deck:'committed-seed' previews Simone's committed deck without storing it. Every row carries reference{origin, app, comp, text, imageAssetId?}: what the button showed on Singular, to read beside the proposed graphic and to pass to create_draft. Its text is empty, and matching is by name only, until import_singular_extract has stored the old compositions; then matching compares what each one showed first.`,z.object({deck:z.enum(['stored','committed-seed']).default('stored'),dryRun:z.boolean().default(true),bind:z.array(rowId).min(1).max(400).optional().describe('Covered row ids to bind, from a dry run.'),expectedVersion:version.min(1).optional(),view:z.enum(['compact','full']).default('compact').describe("compact: one short line per button. full: every field, including candidate scores and each defect's sentence."),status:z.enum(['covered','needs-review','needs-a-graphic']).optional().describe('Show only the rows with this status.')}).strict(),{readOnlyHint:false});
 // T3 - Singular reference material: what each old composition showed, beside every conversion row and matched by content.
 register('import_singular_extract',`Store a Singular.live extract as ${identity.shortName} reference material: for each composition only its app, name, layer and text (title, accent title and text), and optionally a picture of the old slide (imageAssetId from upload_asset). convert_singular_deck then shows each button's old text beside the proposed graphic, matches by what the composition showed as well as its name, and flags buttons whose composition no longer exists in an imported app. Pass the extract inline, or importId for a file dropped on open_import_dropzone kind 'singular-extract'. Either shape is read: the first pass's {apps:[{label (the Companion connection label, e.g. kab), name, id, subcompositions:[{id, name, layer, template, fields:{<fieldId>:{title, type, value}}, notes}]}]}, or the flat {apps:[{label, rootName}], subcompositions:[{id, name, parentApp, layer, fields}]}, grouped by parentApp. Anything that looks like a credential (a Singular control link, token, key or password) is refused and nothing is stored. Apps named replace the stored apps of the same label; others are kept. Dry run by default; a stored extract needs its expectedVersion.`,z.object({extract:z.union([SINGULAR_EXTRACT,SINGULAR_EXTRACT_FLAT]).optional(),importId:z.string().regex(/^import_[a-f0-9]{32}$/,{message:'Pass the importId open_import_dropzone returned (import_ followed by 32 hex characters).'}).optional().describe('A ready singular-extract import (get_import), instead of extract.'),dryRun:z.boolean().default(true),expectedVersion:version.min(1).optional().describe('The stored version a dry run reported, required once reference material is stored.')}).strict(),{readOnlyHint:false});
}
