import {z} from 'zod/v4';
import {type McpIdentity,type RegisterTool,version} from './shared';

// The stored Companion deck (Track C). Each packet appends its tools in its own block.
export function registerDeckTools(register:RegisterTool,identity:McpIdentity){
 // C4 (R-C7, R-C9) - a deck seeded from a Companion export, and its Singular buttons converted to published graphics.
 const rowId=z.string().regex(/^\d{1,2}\/\d\/\d$/,{message:'A row id is "page/row/column" as convert_singular_deck returns it, for example "3/0/5".'});
 register('seed_deck_from_export',`Seed the ${identity.shortName} Companion deck from a Companion 5 full export: every page, position, label and colour is kept, Companion's own page up / number / down buttons stay, camera and OBS buttons are carried as they are, and each Singular.live graphic button becomes a placeholder that convert_singular_deck can bind. Every connection's settings and passwords are discarded on the server before anything is kept, and the uploaded file itself is never stored. Pass export (the .companionconfig file, base64) or useCommittedSeed:true for Simone's 14 September deck. Dry run by default; replacing a stored deck needs its expectedVersion. Only TBI's deck is seeded this way; a deck built from a released preset is changed with the deck tools instead.`,z.object({export:z.string().min(16).max(1_000_000).optional().describe('The .companionconfig file exactly as Companion exported it (gzip or JSON), base64-encoded. It is read in memory and dropped; only the derived deck is kept.'),fileName:z.string().min(1).max(160).optional(),useCommittedSeed:z.boolean().optional().describe("Use Simone's deck as exported on 14 September 2026 (already derived, no upload needed)."),expectedVersion:version.min(1).optional().describe('The stored deck version you read, required to replace a stored deck.'),dryRun:z.boolean().default(true)}).strict(),{readOnlyHint:false,destructiveHint:true});
 register('convert_singular_deck',`Match every Singular.live button on the stored ${identity.shortName} deck to a published graphic, by the same forgiving title search prepare_service_from_setlist uses. Each button comes back Covered (one clear match), Needs review (several candidates, or a defect to settle) or Needs a graphic, with defects named: two presses firing different graphics, a label naming a different prayer than it fires, two buttons with one label on a page, working notes in a label. Dry run by default. With dryRun:false, expectedVersion and bind (row ids from the dry run), only Covered rows are bound, each becoming a one-press key with the Requested and Rendered lights; anything else named is refused and nothing changes. deck:'committed-seed' previews Simone's committed deck without storing it.`,z.object({deck:z.enum(['stored','committed-seed']).default('stored'),dryRun:z.boolean().default(true),bind:z.array(rowId).min(1).max(400).optional().describe('Covered row ids to bind, from a dry run.'),expectedVersion:version.min(1).optional(),view:z.enum(['compact','full']).default('compact').describe("compact: one short line per button. full: every field, including candidate scores and each defect's sentence."),status:z.enum(['covered','needs-review','needs-a-graphic']).optional().describe('Show only the rows with this status.')}).strict(),{readOnlyHint:false});
}
