import {z} from 'zod/v4';
import {MOTION_ELEMENTS,MOTION_PRESETS} from '../layout-definitions';
import {type McpIdentity,type RegisterTool,version} from './shared';

// Layouts as data (packet L3, R-L4). Operations live in lib/layout-tools.ts.
//
// Ids: these tools take any id in Companion's grammar as a string (the layout may not exist yet,
// or may be a draft), and the operation answers an unknown one in a sentence. The existing tools'
// `layout` fields keep shared.ts layoutId(): an enum built from the registry each time a server is
// built, after the workspace's published layouts are registered (app/api/mcp/route.ts). So a
// published data layout is accepted by create_draft on the very next call, and every existing
// tool's recorded schema is unchanged while a workspace has none.
const layoutId=z.string().regex(/^[a-z][a-z0-9_-]{0,39}$/,{message:'A layout id starts with a letter and uses only a-z, 0-9, _ and -, up to 40 characters.'}).describe('A layout id from list_layouts (built-in: bottom, left, right, corner, nameplate).');
const px=(max:number)=>z.number().int().min(0).max(max);
const lineHeight=z.number().min(.8).max(2.5);
const align=z.enum(['start','end','natural']).describe('start/end follow the channel\'s own direction; natural aligns each line to its own script\'s start.');
const channelShape={y:px(1080),height:px(1080).min(1),fontSize:z.number().int().min(20).max(120),lineHeight,align};
const channel=z.object({...channelShape,direction:z.enum(['ltr','rtl']).optional()}).strict();
const single=z.object(channelShape).strict();
const fill=z.object({denominator:z.number().int().min(1).max(1080),sparseBelow:z.number().min(0).max(1)}).strict();
// Every card field is optional here: the card given is merged into the one cloned or stored, field by field.
const cardPatch=z.object({
 frame:z.object({anchor:z.enum(['top-left','top-right','bottom-left','bottom-right']),insetX:px(1920),insetY:px(1080),width:z.number().int().min(40).max(1920),height:z.number().int().min(40).max(1080)}).partial().strict().optional(),
 surface:z.object({radius:px(200),stripHeight:px(1080),ruleHeight:px(1080)}).partial().strict().optional(),
 logo:z.object({x:px(1920),y:px(1080),size:px(1080)}).partial().strict().optional(),
 title:z.object({x:px(1920),y:px(1080),width:px(1920).min(1),height:px(1080).min(1),fontSize:z.number().int().min(20).max(120),lineHeight,accentWidth:px(1920),accentGap:px(1920)}).partial().strict().optional(),
 body:z.object({x:px(1920),width:px(1920).min(1),hebrew:channel.partial().optional(),latin:channel.partial().optional(),single:single.partial().optional()}).partial().strict().optional(),
 fit:z.object({strategy:z.literal('shrink-to-floor'),floor:z.number().int().min(20).max(120),maxSteps:z.number().int().min(0).max(120),glyphTolerance:z.number().int().min(0).max(40),fill:fill.nullable(),heightCeiling:z.number().int().min(1).max(1080).nullable()}).partial().strict().optional(),
}).strict().describe('Card geometry in card-local px (x from the card\'s left edge, y from its top); frame.anchor pins the card to a corner of the 1920x1080 frame, insetX/insetY from those edges. Only the fields you give change.');
const capabilities=z.object({sets:z.boolean(),oneBlockPerSlide:z.boolean(),translation:z.literal(false)}).partial().strict().describe('sets: a long reading may become a set in this layout; oneBlockPerSlide: each slide takes one source block. A card never shows a translated third line.');
const track=z.object({element:z.enum(MOTION_ELEMENTS),direction:z.enum(['In','Out']),effect:z.object({effect:z.enum(['fade','scale','translate','none']).optional(),property:z.enum(['none','x','y','xAndY','up','down','left','right']).optional(),easing:z.object({easing:z.enum(['power1','power2','power3','power4']).optional(),inOut:z.enum(['in','out','inOut']).optional()}).strict().optional()}).strict().optional(),keyframes:z.tuple([z.number().min(0).max(5),z.number().min(0).max(5)]).optional()}).strict();
const motion=z.union([z.object({preset:z.enum(MOTION_PRESETS)}).strict(),z.object({tracks:z.array(track).min(1).max(64),duration:z.object({In:z.number().min(.05).max(5),Out:z.number().min(.05).max(5)}).strict()}).strict()]).describe('card-scale: the bars scale in from the anchored edge and the text fades (the corner card\'s); fade: every part fades. Or explicit tracks. Replaces the motion as a whole.');
const label=z.string().min(1).max(60).describe('The operator\'s name for the layout, for example "Response card".');
const sample=z.object({label:z.string().min(1).max(80).optional(),title:z.string().min(1).max(100),accentTitle:z.string().min(1).max(60).optional(),hebrew:z.string().min(1).max(400).optional(),transliteration:z.string().min(1).max(400).optional(),english:z.string().min(1).max(400).optional()}).strict().describe('Sample text: a title, and Hebrew with or without transliteration, or one English line.');

export function registerLayoutsTools(register:RegisterTool,identity:McpIdentity){
 register('list_layouts',`Every layout ${identity.shortName} can use: the five built in (bottom lower third, left and right panels, corner card, nameplate) and this congregation's own card layouts, with each one's newest version, whether it is a draft or published, and publishedVersion. Only a layout with a published version is accepted by create_draft. Read only; get_layout has the full definition.`,z.object({}).strict(),{readOnlyHint:true});
 register('get_layout','Read one layout in full: a data layout\'s card definition (geometry, fit, motion) at its newest version or the version named, every version with its status, how many published graphics pin each version (pinnedGraphics), and the static check. A built-in layout is shown read only, with its card when it has one (corner). Read only.',z.object({layoutId,version:version.min(1).optional()}).strict(),{readOnlyHint:true});
 register('create_layout',`Make a new ${identity.shortName} card layout by copying an existing one (from: corner, or a layout of your own at its published version unless fromVersion says otherwise), with any changes given. It is saved as draft version 1: nothing uses it until publish_layout. The lower third and the panels are built-in CSS and cannot be copied. Example: a top-right Response card is from:'corner' with card.frame.anchor:'top-right'.`,z.object({layoutId:layoutId.describe('The new layout\'s id: a-z, 0-9, _ and -, starting with a letter, up to 40 characters. Companion carries it in variable names.'),from:layoutId.describe('The layout to copy: corner, or one of this congregation\'s own.'),fromVersion:version.min(1).optional(),label:label.optional(),capabilities:capabilities.optional(),card:cardPatch.optional(),motion:motion.optional()}).strict(),{readOnlyHint:false});
 register('update_layout','Change a data layout, with the newest version get_layout returned as expectedVersion. Only a draft is ever written: a draft is changed in place, and changing a published version saves your change as a new draft version above it, leaving the published one and every graphic that pins it exactly as they are. card is merged field by field; motion is replaced whole.',z.object({layoutId,expectedVersion:version.min(1),label:label.optional(),capabilities:capabilities.optional(),card:cardPatch.optional(),motion:motion.optional()}).strict(),{readOnlyHint:false});
 register('validate_layout','Check a data layout without a browser: the definition parses, the card lies inside the 1920x1080 frame and every part inside the card, no text channel or the logo overlaps another, the shrink floor is at least 20 px and below every font size, the id fits Companion\'s grammar, and every face the card draws with is a registered overlay font. Returns each check and plain sentences for what fails. Read only.',z.object({layoutId,version:version.min(1).optional()}).strict(),{readOnlyHint:true});
 register('preview_layout','See a layout, draft or published, with text in it: sample texts and/or up to six drafts by id (drawn in this layout, whatever layout they are in), each fitted in a browser on the server and returned as a frame, in order, with its verdict. With neither, the three standard samples publish_layout checks. Saves nothing and publishes nothing; nothing reaches the output.',z.object({layoutId,version:version.min(1).optional(),samples:z.array(sample).min(1).max(6).optional(),draftIds:z.array(z.string().min(1).max(200)).min(1).max(6).optional(),includePreviewImages:z.boolean().optional().describe('false skips the frames and returns only the verdicts.')}).strict(),{readOnlyHint:true});
 register('publish_layout',`Publish a data layout's draft version (expectedVersion) so ${identity.shortName} graphics can use it: create_draft with layout set to its id, then ship_draft. It first runs the static check and fits the standard samples (plus up to three of your own) on the server, and publishes only if every one passes; otherwise it stops with the reasons and publishes nothing. A published version never changes. Graphics already published in an older version keep it until rebase_to_layout.`,z.object({layoutId,expectedVersion:version.min(1),samples:z.array(sample).min(1).max(3).optional()}).strict(),{readOnlyHint:false});
 register('rebase_to_layout','Move published graphics that pin an older version of a data layout to its newest published version (expectedVersion), each by ship_draft: server fit, then publish, so each one is checked in the new geometry. A dry run unless dryRun:false; the dry run lists what would move. Graphics with unpublished changes are skipped with the reason, so a rebase changes nothing but the layout. draftIds narrows it. A long run stops starting new graphics near the time limit; call again to continue.',z.object({layoutId,expectedVersion:version.min(1),dryRun:z.boolean().optional(),draftIds:z.array(z.string().min(1).max(200)).min(1).max(200).optional()}).strict(),{readOnlyHint:false});
}
