'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import SignInCard from './sign-in-card';
import styles from './health.module.css';

type StatusPayload={generatedAt:number;overall:'ready'|'attention'|'unavailable';playback:{status:string;relay:{status:string};current:{known:boolean;cue:string|null;name:string|null;revision:number|null};outputs:{status:string;connected:number;freshnessSeconds:number};controllers:{status:string;reason:string}};synchronization:{status:string;liveVersion:string|null;authoringVersion:string|null;checkedAt:number};authoring:{status:string;latestPublicationAt:number|null;publishedVisibleCount:number|null;publishedCount?:number;draftCount?:number;revisionCount?:number;databaseBytes?:number};providerUsage?:Array<{provider:string;status:string;measuredAt:number|null;window:string|null;used:number|null;limit:number|null;unit:string|null;dashboardUrl:string;note:string}>;budget?:{scope:string;targetMonthlyUsd:number;reviewMonthlyUsd:number;reportedMonthlyUsd:number;budgetStatus:string;reportedProviders:number;totalProviders:number;conclusive:boolean;note:string}};
const when=(value:number|null|undefined)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(value):'Not available';
const bytes=(value:number|undefined)=>typeof value==='number'?new Intl.NumberFormat(undefined,{style:'unit',unit:'megabyte',maximumFractionDigits:1}).format(value/1_000_000):'Available to administrators';
const label=(value:string)=>value.replaceAll('-',' ').replace(/^./,c=>c.toUpperCase());
function UsageReportForm({provider,onSaved}:{provider:string;onSaved:()=>void}){const [open,setOpen]=useState(false),[used,setUsed]=useState(''),[limit,setLimit]=useState(''),[unit,setUnit]=useState('USD'),[window,setWindow]=useState(()=>new Date().toISOString().slice(0,7)),[message,setMessage]=useState('');async function save(event:FormEvent){event.preventDefault();setMessage('Saving…');try{const response=await fetch('/api/health',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,used:Number(used),limit:Number(limit),unit,window,measuredAt:Date.now()})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not save this report.');setMessage('Saved as an owner-reported value.');setOpen(false);onSaved()}catch(error){setMessage(error instanceof Error?error.message:'Could not save this report.')}}return <div className={styles.report}>{!open?<button type="button" onClick={()=>setOpen(true)}>Report current usage</button>:<form onSubmit={event=>void save(event)}><label>Used<input required type="number" min="0" step="any" value={used} onChange={e=>setUsed(e.target.value)}/></label><label>Limit<input required type="number" min="0.01" step="any" value={limit} onChange={e=>setLimit(e.target.value)}/></label><label>Unit<input required maxLength={20} value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>Billing month<input required type="month" value={window} onChange={e=>setWindow(e.target.value)}/></label><div><button type="submit">Save report</button><button type="button" onClick={()=>setOpen(false)}>Cancel</button></div></form>}{message&&<small role="status">{message}</small>}</div>}
export default function HealthClient({workspaceName}:{workspaceName:string}){
 const [data,setData]=useState<StatusPayload|null>(null),[error,setError]=useState(''),[updating,setUpdating]=useState(true),[needsSignIn,setNeedsSignIn]=useState(false);
 // A 401 is the one failure with a way out for the reader, so it gets the shared sign-in card;
 // every other failure keeps the "temporarily unavailable" wording.
 const refresh=useCallback(async()=>{setUpdating(true);try{const response=await fetch('/api/health',{cache:'no-store',signal:AbortSignal.timeout(6500)});if(response.status===401){setNeedsSignIn(true);throw new Error('Sign in to see workspace health.')}const body=await response.json();if(!response.ok)throw new Error('The health check is temporarily unavailable.');setNeedsSignIn(false);setData(body);setError('')}catch(e){setError(e instanceof Error?e.message:'The health check is temporarily unavailable.')}finally{setUpdating(false)}},[]);
 useEffect(()=>{const initial=setTimeout(()=>void refresh(),0);const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},60_000);const visible=()=>{if(document.visibilityState==='visible')void refresh()};document.addEventListener('visibilitychange',visible);return()=>{clearTimeout(initial);clearInterval(timer);document.removeEventListener('visibilitychange',visible)}},[refresh]);
 if(!data&&needsSignIn&&!updating)return <SignInCard description="Workspace health reports what is ready for a service: live playback, the graphics output, library synchronization, and the authoring database." onRetry={()=>void refresh()}/>;
 if(!data)return <section className={styles.empty}><h2>{updating?'Checking the workspace…':error}</h2>{!updating&&<><p>Existing graphics outputs may still be connected even when this signed-in health check cannot reach the account database.</p><Link href="/access">Open account</Link> <button onClick={()=>void refresh()}>Try again</button></>}</section>;
 return <>
  <section className={`${styles.overall} ${styles[data.overall]}`}><div><span>System check</span><strong>{label(data.overall)}</strong></div><p>{data.overall==='ready'?'Playback and authoring answered, the live catalog matches, and a graphics output is present.':data.overall==='attention'?(data.playback.outputs.connected===0?'Playback and authoring answered, but no graphics output is connected in the current freshness window.':'Playback is available, but authoring or synchronization needs attention.'):data.playback.status==='not-configured'?'The live relay is not configured. Finish workspace setup before relying on this output path.':'The live playback check did not answer. Use the fallback in the service guide.'}</p><button onClick={()=>void refresh()} disabled={updating}>{updating?'Checking…':'Check now'}</button></section>
  {error&&<p className={styles.stale} role="status">Latest refresh failed. Showing the last successful observation from {when(data.generatedAt)}.</p>}
  <div className={styles.grid}>
   <article><span>Live playback</span><h2>{label(data.playback.status)}</h2><dl><div><dt>Relay</dt><dd>{label(data.playback.relay.status)}</dd></div><div><dt>Current graphic</dt><dd>{data.playback.current.name??(data.playback.current.known?'Clear':'Unavailable')}</dd></div><div><dt>Revision</dt><dd>{data.playback.current.revision??'Unavailable'}</dd></div></dl></article>
   <article><span>Graphics output</span><h2>{label(data.playback.outputs.status)}</h2><p>{data.playback.outputs.status==='connected'||data.playback.outputs.status==='none-seen'?`${data.playback.outputs.connected} browser output${data.playback.outputs.connected===1?' is':'s are'} present within the ${data.playback.outputs.freshnessSeconds}-second window.`:'Output presence is unavailable. This is not zero.'}</p><small>Controller presence: unavailable. {data.playback.controllers.reason}</small></article>
   <article><span>Library synchronization</span><h2>{label(data.synchronization.status)}</h2><p>{data.synchronization.status==='pending'?'A published library change has not reached the live relay yet.':'Compared at '+when(data.synchronization.checkedAt)+'.'}</p><small>Live {data.synchronization.liveVersion??'unavailable'} · Authoring {data.synchronization.authoringVersion??'unavailable'}</small></article>
   <article><span>Authoring database</span><h2>{label(data.authoring.status)}</h2><dl><div><dt>Latest publication</dt><dd>{when(data.authoring.latestPublicationAt)}</dd></div><div><dt>Published, visible</dt><dd>{data.authoring.publishedVisibleCount??'Unavailable'}</dd></div>{data.authoring.publishedCount!==undefined&&<><div><dt>Published records / drafts</dt><dd>{data.authoring.publishedCount} / {data.authoring.draftCount}</dd></div><div><dt>Revisions</dt><dd>{data.authoring.revisionCount}</dd></div><div><dt>Database size</dt><dd>{bytes(data.authoring.databaseBytes)}</dd></div></>}</dl></article>
  </div>
  {data.providerUsage&&<section className={styles.providers}><div className={styles.sectionHeading}><div><span>Administrator view</span><h2>Provider usage and budget review</h2></div><p>{data.budget?.scope}: target under ${data.budget?.targetMonthlyUsd}/month; review before ${data.budget?.reviewMonthlyUsd}/month.</p></div>{data.budget&&<p className={styles.budgetNotice}><strong>{data.budget.budgetStatus==='review-now'?'Review costs now':data.budget.budgetStatus==='above-target'?'Above the preferred target':data.budget.budgetStatus==='within-target'?'Within the preferred target':'Monthly total unavailable'}</strong> · {data.budget.reportedProviders}/{data.budget.totalProviders} providers reported in USD{data.budget.reportedProviders?` · entered-report sum $${data.budget.reportedMonthlyUsd}`:''}. {data.budget.note}</p>}<div className={styles.providerGrid}>{data.providerUsage.map(item=><article key={item.provider}><h3>{item.provider}</h3><strong>{item.status==='reported'&&item.used!==null&&item.limit!==null?`${item.used} / ${item.limit} ${item.unit}`:'Usage unavailable'}</strong>{item.status==='reported'&&item.used!==null&&item.limit!==null&&item.used/item.limit>=.8&&<p className={styles.usageWarning}>At least 80% of the entered provider limit. Review the dashboard.</p>}<p>{item.note}</p><small>{item.measuredAt?`${item.window} · reported ${when(item.measuredAt)}`:'No measured window'}</small><a href={item.dashboardUrl} target="_blank" rel="noreferrer">Open provider dashboard</a><UsageReportForm provider={item.provider} onSaved={()=>void refresh()}/></article>)}</div></section>}
  <section className={styles.actions}><div><span>Recovery</span><h2>Need to act?</h2><p>Use the service fallback, backup, account, and restore rehearsal guides. Health checks never put a graphic on air.</p></div><Link href="/help">Open Help</Link></section>
  <footer>Last successful observation: {when(data.generatedAt)} · {workspaceName} workspace</footer>
 </>;
}

