#!/usr/bin/env node
// Copies the shared Companion palette (lib/companion-deck/palette.ts, the deck renderer's) into
// src/palette.ts, so the module's presets colour a cue by the same role rule and values as the deck.
// The module cannot import web code at runtime, so the share happens here, at build time: `npm run
// build` runs this before tsc. The copy is committed so tests and lint work without a build, and
// tests/palette.test.ts (here) and tests/companion-palette.test.ts (repo root) fail when it is stale.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const moduleRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
export const PALETTE_SOURCE = join(moduleRoot, '..', 'lib', 'companion-deck', 'palette.ts')
export const PALETTE_COPY = join(moduleRoot, 'src', 'palette.ts')

const BANNER = '// Generated by companion/scripts/write-palette.mjs from lib/companion-deck/palette.ts. Do not edit;\n// change the source and run `npm run build` (or `node scripts/write-palette.mjs`) in companion/.\n\n'

/** The exact text src/palette.ts must hold for a given source. */
export const paletteCopy = (source) => BANNER + source.replace(/\r\n/g, '\n')

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const source = readFileSync(PALETTE_SOURCE, 'utf8')
  writeFileSync(PALETTE_COPY, paletteCopy(source))
  console.log('Wrote src/palette.ts from lib/companion-deck/palette.ts')
}
