'use client';
import {useEffect,useState,useRef} from 'react';
export default function Console(){const[key,setKey]=useState('');const[draft,setDraft]=useState('');const[cues,setCues]=useState<any[]>([]);const[state,setState]=useState<any>(null);const[error,setError]=useState('');const[connected,setConnected]=useState(false);const[pending,setPending]=useState(false);const client=useRef('');const sequence=useRef(0);
const accept=(s:any)=>setState((prev:any)=>!prev||s.revision>prev.revision||(s.revision===prev.revision&&s.serverTime>=prev.serverTime)?s:prev);
useEffect(()=>{client.current=sessionStorage.getItem('crc-controller-id')||crypto.randomUUID();sessionStorage.setItem('crc-controller-id',client.current);sequence.current=Number(sessionStorage.getItem('crc-controller-sequence')||0);setKey(sessionStorage.getItem('crc-control-key')||'')},[]);
useEffect(()=>{if(!key)return;let stopped=false,timer:ReturnType<typeof setTimeout>;const headers={Authorization:`Bearer ${key}`};fetch('/api/catalog',{headers}).then(async r=>{if(!r.ok)throw Error('Control key not accepted');setCues(await r.json())}).catch(e=>setError(e.message));const poll=async()=>{try{const r=await fetch('/api/state',{headers,cache:'no-store',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error('Connection unavailable');const s=await r.json();if(!stopped){accept(s);setConnected(true)}}catch{if(!stopped)setConnected(false)}finally{if(!stopped)timer=setTimeout(poll,700)}};void poll();return()=>{stopped=true;clearTimeout(timer)}},[key]);
async function command(action:string,cue?:string){const nextSequence=++sequence.current;sessionStorage.setItem('crc-controller-sequence',String(nextSequence));setPending(true);setError('');try{const r=await fetch('/api/command',{method:'POST',signal:AbortSignal.timeout(5000),headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({commandId:crypto.randomUUID(),clientId:client.current,sequence:nextSequence,action,cue})});if(!r.ok)throw Error('Command not confirmed. Check requested and rendered status.');const result:any=await r.json();accept(result);return {revision:result.revision,cue:result.cue}}catch(e){setError(String(e));throw e}finally{setPending(false)}}
useEffect(()=>{if(!key)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
const register=(tool:any)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
register({name:'read_overlay_status',description:'Read requested cue and recent graphics-output acknowledgments. Rendered does not establish that vMix or OBS is on air.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const r=await fetch('/api/state',{headers:{Authorization:`Bearer ${key}`},signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error('Status unavailable');const s=await r.json();accept(s);return s}});
register({name:'set_overlay_cue',description:'Change the CRC test graphics output: show a known prayer, animate out, or clear immediately. This controls output, not just preview.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['in','clear','cut']},cue:{type:'string',enum:cues.map(c=>c.id)}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||!['in','clear','cut'].includes(input.action)||Object.keys(input).some(k=>!['action','cue'].includes(k))||(input.action==='in'&&!cues.some(c=>c.id===input.cue)))throw Error('Invalid action or prayer cue');return command(input.action,input.cue)}});
return()=>lifecycle.abort()},[key,cues]);
const renderers=state?.renderers??[];const settled=renderers.filter((r:any)=>r.revision===state.revision&&r.cue===state.cue&&r.phase==='settled');const name=cues.find(c=>c.id===state?.cue)?.name||'Clear';
return <main className="console"><header><div><span className="eyebrow">CENTRAL REFORM CONGREGATION</span><h1>Overlay control</h1></div><span className="badge">CRC TEST OUTPUT</span></header>
{!key?<form className="access" onSubmit={e=>{e.preventDefault();sessionStorage.setItem('crc-control-key',draft);setKey(draft)}}><h2>Connect this control surface</h2><label>Control key<input type="password" autoComplete="off" value={draft} onChange={e=>setDraft(e.target.value)} required/></label><button>Connect</button></form>:<>
<section className="status"><div><span>Requested</span><strong>{connected?name:'Connection lost'}</strong></div><div><span>Graphics output</span><strong>{!connected?'Unknown':!renderers.length?'No output connected':settled.length===renderers.length?`Rendered · ${name}`:'Waiting for output'}</strong></div><p>Rendered confirms the browser graphic. Check vMix or OBS to confirm it is on air.</p></section>
<div className="workspace"><section className="preview"><iframe title="Graphics preview" src={`/output?preview=1#key=${encodeURIComponent(key)}`}/><div className="preview-caption">Preview · camera stays full frame</div></section><section className="library"><h2>Prayer cues</h2>{cues.map(c=><button className={state?.cue===c.id?'cue selected':'cue'} key={c.id} disabled={pending||!connected} onClick={()=>void command('in',c.id).catch(()=>{})}>{c.name}<small>{c.layout==='left'?'Left panel':'Lower third'}</small></button>)}<button disabled={pending||!connected} onClick={()=>void command('clear').catch(()=>{})}>Animate out</button><button className="cut" disabled={!connected} onClick={()=>void command('cut').catch(()=>{})}>Clear immediately</button></section></div>
<details><summary>Connect vMix, OBS, or Companion</summary><p>Use the output-only link from your connection sheet in a 1920 × 1080 Browser input. Preview above does not count as a connected output.</p><p>Companion: POST to <code>/api/command</code> with an Authorization bearer control key and JSON <code>{'{"action":"in","cue":"…"}'}</code>. Use explicit In and Out actions; button state must come from feedback, not a local toggle.</p><button onClick={()=>{sessionStorage.removeItem('crc-control-key');sessionStorage.removeItem('crc-output-key');setKey('');setCues([])}}>Disconnect this control surface</button></details></>}{error&&<p role="alert" className="error">{error}</p>}<footer>Three reference cues · Appearance still under comparison with Singular</footer></main>}

