'use client';
import {useEffect,useState,useRef} from 'react';
export default function Console(){const[key,setKey]=useState('');const[draft,setDraft]=useState('');const[cues,setCues]=useState<any[]>([]);const[state,setState]=useState<any>(null);const[error,setError]=useState('');const[connected,setConnected]=useState(false);const[pending,setPending]=useState(false);const client=useRef('');const sequence=useRef(0);const catalogVersion=useRef('');
const accept=(s:any)=>setState((prev:any)=>!prev||s.revision>prev.revision||(s.revision===prev.revision&&s.serverTime>=prev.serverTime)?s:prev);
useEffect(()=>{client.current=sessionStorage.getItem('crc-controller-id')||crypto.randomUUID();sessionStorage.setItem('crc-controller-id',client.current);sequence.current=Number(sessionStorage.getItem('crc-controller-sequence')||0);setKey(sessionStorage.getItem('crc-control-key')||'')},[]);
useEffect(()=>{if(!key)return;let stopped=false;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),4000);setCues([]);catalogVersion.current='';setError('');fetch('/api/catalog',{headers:{Authorization:`Bearer ${key}`},signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Cue catalog unavailable. Check the control key.');const next=await r.json();const version=r.headers.get('X-CRC-Catalog-Version');if(!Array.isArray(next)||next.some(c=>!c||typeof c.id!=='string'||typeof c.name!=='string'||typeof c.layout!=='string'||!c.texts||typeof c.texts!=='object'||!Array.isArray(c.animations)||!c.duration||typeof c.duration!=='object'))throw Error('Cue catalog unavailable: invalid catalog.');if(!stopped){catalogVersion.current=version||'';setCues(next)}}).catch(e=>{if(!stopped){setCues([]);setError(e instanceof Error&&e.name==='AbortError'?'Cue catalog unavailable (request timed out).':e instanceof Error?e.message:'Cue catalog unavailable. Check the control key.')}}).finally(()=>clearTimeout(timeout));return()=>{stopped=true;controller.abort();clearTimeout(timeout)}},[key]);
useEffect(()=>{if(!key)return;let stopped=false,timer:ReturnType<typeof setTimeout>;const headers={Authorization:`Bearer ${key}`};const poll=async()=>{try{const r=await fetch('/api/state',{headers,cache:'no-store',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error('Connection unavailable');const s=await r.json();if(!stopped&&s.catalogVersion&&s.catalogVersion!==catalogVersion.current){const catalog=await fetch('/api/catalog',{headers,cache:'no-store',signal:AbortSignal.timeout(4000)});const next=await catalog.json();const version=catalog.headers.get('X-CRC-Catalog-Version');if(!catalog.ok||version!==s.catalogVersion||!Array.isArray(next)||next.some(c=>!c||typeof c.id!=='string'||typeof c.name!=='string'||typeof c.layout!=='string'||!c.texts||typeof c.texts!=='object'||!Array.isArray(c.animations)||!c.duration||typeof c.duration!=='object'))throw Error('Cue catalog unavailable: refresh failed.');if(!stopped){catalogVersion.current=version||'';setCues(next)}}if(!stopped){accept(s);setConnected(true)}}catch(e){if(!stopped){if(e instanceof Error&&e.message.startsWith('Cue catalog'))setError(e.message);setConnected(false)}}finally{if(!stopped)timer=setTimeout(poll,700)}};void poll();return()=>{stopped=true;clearTimeout(timer)}},[key]);
async function command(action:string,cue?:string){const nextSequence=++sequence.current;sessionStorage.setItem('crc-controller-sequence',String(nextSequence));setPending(true);setError('');try{const r=await fetch('/api/command',{method:'POST',signal:AbortSignal.timeout(5000),headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({commandId:crypto.randomUUID(),clientId:client.current,sequence:nextSequence,action,cue})});if(!r.ok)throw Error('Command not confirmed. Check requested and rendered status.');const result:any=await r.json();accept(result);return {revision:result.revision,cue:result.cue}}catch(e){setError(String(e));throw e}finally{setPending(false)}}
useEffect(()=>{if(!key)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
const register=(tool:any)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
register({name:'read_overlay_status',description:'Read requested cue and recent graphics-output acknowledgments. Rendered does not establish that vMix or OBS is on air.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const r=await fetch('/api/state',{headers:{Authorization:`Bearer ${key}`},signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error('Status unavailable');const s=await r.json();accept(s);return s}});
register({name:'set_overlay_cue',description:'Change the CRC test graphics output: show a known prayer, animate out, or clear immediately. This controls output, not just preview.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['in','clear','cut']},cue:{type:'string',enum:cues.map(c=>c.id)}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||!['in','clear','cut'].includes(input.action)||Object.keys(input).some(k=>!['action','cue'].includes(k))||(input.action==='in'&&!cues.some(c=>c.id===input.cue)))throw Error('Invalid action or prayer cue');return command(input.action,input.cue)}});
return()=>lifecycle.abort()},[key,cues]);
const renderers=state?.renderers??[];const settled=renderers.filter((r:any)=>r.revision===state.revision&&r.cue===state.cue&&r.phase==='settled');const catalogReady=cues.length>0;const name=cues.find(c=>c.id===state?.cue)?.name||'Clear';const layoutName=(layout:string)=>layout==='left'?'Left panel':layout==='right'?'Right panel':layout==='bottom'?'Bottom': 'Overlay';
return <main className="console"><header><div><span className="eyebrow">CENTRAL REFORM CONGREGATION</span><h1>Overlay control</h1></div><span className="badge">CRC TEST OUTPUT</span></header>
{!key?<form className="access" onSubmit={e=>{e.preventDefault();sessionStorage.setItem('crc-control-key',draft);setKey(draft)}}><h2>Connect this control surface</h2><label>Control key<input type="password" autoComplete="off" value={draft} onChange={e=>setDraft(e.target.value)} required/></label><button>Connect</button></form>:<>
<section className="status"><div><span>Requested</span><strong>{!connected?'Connection lost':!catalogReady?'Catalog unavailable':name}</strong></div><div><span>Graphics output</span><strong>{!connected?'Unknown':!renderers.length?'No output connected':settled.length===renderers.length?`Rendered · ${name}`:'Waiting for output'}</strong></div><p>Rendered confirms the browser graphic. Check vMix or OBS to confirm it is on air.</p></section>
<div className="workspace"><section className="preview"><iframe title="Graphics preview" src={`/output?preview=1#key=${encodeURIComponent(key)}`}/><div className="preview-caption">Preview · camera stays full frame</div></section><section className="library"><h2>Prayer cues</h2>{cues.map(c=><button className={state?.cue===c.id?'cue selected':'cue'} key={c.id} disabled={pending||!connected} onClick={()=>void command('in',c.id).catch(()=>{})}>{c.name}<small>{layoutName(c.layout)}</small></button>)}<button disabled={pending||!connected} onClick={()=>void command('clear').catch(()=>{})}>Animate out</button><button className="cut" disabled={!connected} onClick={()=>void command('cut').catch(()=>{})}>Clear immediately</button></section></div>
<details><summary>Connect vMix, OBS, or Companion</summary><p>For rehearsal, install the native CRC Overlays Companion module and use its supplied presets. Point the output-only link from your connection sheet at a 1920 × 1080 Browser input in vMix or OBS. Preview above does not count as a connected output.</p><p>The native Companion module supplies ordered commands, retries, and requested/rendered/disconnected feedback. Use its presets for In, Animate out, and Clear immediately. Generic HTTP requests to <code>/api/command</code> are a legacy fallback and do not provide sequencing or retry identity.</p><button onClick={()=>{sessionStorage.removeItem('crc-control-key');sessionStorage.removeItem('crc-output-key');setKey('');setCues([])}}>Disconnect this control surface</button></details></>}{error&&<p role="alert" className="error">{error}</p>}<footer>{cues.length} catalog cues · Rehearsal status live · Visual fidelity still under comparison with Singular</footer></main>}

