import {createHash} from 'node:crypto';
import {db} from './database';

export const ASSET_MAX_BYTES=512*1024,ASSET_MAX_DIMENSION=4096,ASSET_MAX_PIXELS=16_000_000,ASSET_MAX_ITEMS=500;
export type AssetMime='image/png'|'image/jpeg'|'image/webp';
export type AssetMetadata={id:string;name:string;altText:string;mimeType:AssetMime;bytes:number;width:number;height:number;version:number;archived:boolean;published:boolean;createdAt:number;updatedAt:number;createdBy:string;updatedBy:string;privatePreviewUrl:string;publicUrl?:string};
export type AssetRecord=AssetMetadata&{data:Uint8Array};
export class AssetError extends Error{constructor(public code:string,message:string,public status=400){super(message)}}
export class AssetConflictError extends AssetError{constructor(){super('version_conflict','This asset changed in another session. Refresh and try again.',409)}}
export type AssetQueryable={query:(text:string,values?:unknown[])=>Promise<{rows:unknown[];rowCount:number|null}>};
export interface AssetRepository{list(includeArchived?:boolean):Promise<AssetMetadata[]>;count():Promise<number>;get(id:string):Promise<AssetRecord|null>;insert(record:AssetRecord):Promise<boolean>;setArchived(id:string,expectedVersion:number,archived:boolean,actor:string,now:number):Promise<AssetMetadata|null>;markPublished(id:string,now:number):Promise<boolean>}

function urls<T extends Omit<AssetMetadata,'privatePreviewUrl'|'publicUrl'>>(value:T):AssetMetadata{return {...value,privatePreviewUrl:`/api/assets/${encodeURIComponent(value.id)}/preview`,...(value.published?{publicUrl:`/api/assets/${encodeURIComponent(value.id)}/content`}:{})}}
const clone=<T>(value:T):T=>structuredClone(value);
export class MemoryAssetRepository implements AssetRepository{
 records=new Map<string,AssetRecord>();
 async list(includeArchived=false){return [...this.records.values()].filter(item=>includeArchived||!item.archived).sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,ASSET_MAX_ITEMS).map(assetMetadata)}
 async count(){return this.records.size}async get(id:string){const value=this.records.get(id);return value?clone(value):null}
 async insert(record:AssetRecord){if(this.records.has(record.id))return false;this.records.set(record.id,clone(record));return true}
 async setArchived(id:string,expected:number,archived:boolean,actor:string,now:number){const value=this.records.get(id);if(!value||value.version!==expected)return null;const next={...value,archived,version:value.version+1,updatedAt:now,updatedBy:actor};this.records.set(id,next);return assetMetadata(next)}
 async markPublished(id:string,now:number){const value=this.records.get(id);if(!value||value.archived)return false;this.records.set(id,{...value,published:true,publicUrl:`/api/assets/${encodeURIComponent(id)}/content`,updatedAt:now});return true}
}

type AssetRow={id:string;name:string;altText:string;mimeType:AssetMime;bytes:number;width:number;height:number;version:number;archived:boolean;published:boolean;createdAt:number;updatedAt:number;createdBy:string;updatedBy:string;data?:Buffer};
const rowMetadata=(row:AssetRow)=>urls({id:row.id,name:row.name,altText:row.altText,mimeType:row.mimeType,bytes:Number(row.bytes),width:row.width,height:row.height,version:row.version,archived:row.archived,published:row.published,createdAt:Number(row.createdAt),updatedAt:Number(row.updatedAt),createdBy:row.createdBy,updatedBy:row.updatedBy});
const columns=`id,name,alt_text AS "altText",mime_type AS "mimeType",byte_size AS bytes,width,height,version,archived,(published_at IS NOT NULL) AS published,created_at AS "createdAt",updated_at AS "updatedAt",created_by AS "createdBy",updated_by AS "updatedBy"`;
export class PgAssetRepository implements AssetRepository{
 constructor(private connection:AssetQueryable=db){}
 async list(includeArchived=false){const result=await this.connection.query(`SELECT ${columns} FROM workspace_assets WHERE ($1 OR archived=false) ORDER BY updated_at DESC LIMIT ${ASSET_MAX_ITEMS}`,[includeArchived]);return result.rows.map(row=>rowMetadata(row as AssetRow))}
 async count(){const result=await this.connection.query('SELECT count(*)::int AS count FROM workspace_assets');return Number((result.rows[0] as {count:number}|undefined)?.count??0)}
 async get(id:string){const result=await this.connection.query(`SELECT ${columns},data FROM workspace_assets WHERE id=$1`,[id]);const row=result.rows[0] as AssetRow|undefined;if(!row?.data)return null;return {...rowMetadata(row),data:new Uint8Array(row.data)}}
 async insert(value:AssetRecord){const result=await this.connection.query('INSERT INTO workspace_assets(id,name,alt_text,mime_type,byte_size,width,height,data,version,archived,published_at,created_at,updated_at,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,1,false,NULL,$9,$9,$10,$10) ON CONFLICT(id) DO NOTHING',[value.id,value.name,value.altText,value.mimeType,value.bytes,value.width,value.height,Buffer.from(value.data),value.createdAt,value.createdBy]);return Boolean(result.rowCount)}
 async setArchived(id:string,expected:number,archived:boolean,actor:string,now:number){const result=await this.connection.query(`UPDATE workspace_assets SET archived=$3,version=version+1,updated_at=$4,updated_by=$5 WHERE id=$1 AND version=$2 RETURNING ${columns}`,[id,expected,archived,now,actor]);const row=result.rows[0] as AssetRow|undefined;return row?rowMetadata(row):null}
 async markPublished(id:string,now:number){return markAssetPublished(this.connection,id,now)}
}

const rehearsalAssets=new MemoryAssetRepository();
export function defaultAssetRepository():AssetRepository{if(process.env.CRC_AUTHORING_REHEARSAL==='1'){if(process.env.NODE_ENV!=='development'||Boolean(process.env.RELAY_URL))throw new Error('Asset rehearsal storage is allowed only in local development without a relay.');return rehearsalAssets}return new PgAssetRepository()}

function pngSize(data:Uint8Array){if(data.length<45||Buffer.from(data.subarray(0,8)).toString('hex')!=='89504e470d0a1a0a'||Buffer.from(data.subarray(12,16)).toString()!=='IHDR'||Buffer.from(data.subarray(data.length-8,data.length-4)).toString()!=='IEND'||Buffer.from(data).includes(Buffer.from('acTL')))return null;const view=new DataView(data.buffer,data.byteOffset,data.byteLength);return {mimeType:'image/png' as const,width:view.getUint32(16),height:view.getUint32(20)}}
function jpegSize(data:Uint8Array){if(data.length<4||data[0]!==0xff||data[1]!==0xd8||data[data.length-2]!==0xff||data[data.length-1]!==0xd9)return null;for(let offset=2;offset+9<data.length;){if(data[offset]!==0xff){offset++;continue}const marker=data[offset+1];if(marker===0xd9||marker===0xda)break;if(marker>=0xd0&&marker<=0xd7){offset+=2;continue}const length=(data[offset+2]<<8)|data[offset+3];if(length<2||offset+2+length>data.length)return null;if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return {mimeType:'image/jpeg' as const,width:(data[offset+7]<<8)|data[offset+8],height:(data[offset+5]<<8)|data[offset+6]};offset+=2+length}return null}
function webpSize(data:Uint8Array){if(data.length<30||Buffer.from(data.subarray(0,4)).toString()!=='RIFF'||Buffer.from(data.subarray(8,12)).toString()!=='WEBP'||new DataView(data.buffer,data.byteOffset,data.byteLength).getUint32(4,true)+8!==data.length)return null;const chunk=Buffer.from(data.subarray(12,16)).toString();if(chunk==='VP8X'){if(data[20]&0x02)return null;return {mimeType:'image/webp' as const,width:1+data[24]+(data[25]<<8)+(data[26]<<16),height:1+data[27]+(data[28]<<8)+(data[29]<<16)}}if(chunk==='VP8L'){if(data[20]!==0x2f)return null;const bits=data[21]|(data[22]<<8)|(data[23]<<16)|(data[24]<<24);return {mimeType:'image/webp' as const,width:(bits&0x3fff)+1,height:((bits>>14)&0x3fff)+1}}if(chunk==='VP8 '&&data.length>=30&&data[23]===0x9d&&data[24]===0x01&&data[25]===0x2a)return {mimeType:'image/webp' as const,width:(data[26]|(data[27]<<8))&0x3fff,height:(data[28]|(data[29]<<8))&0x3fff};return null}
export function inspectAssetImage(data:Uint8Array){if(!data.length||data.length>ASSET_MAX_BYTES)throw new AssetError('image_too_large',`Choose an image smaller than ${ASSET_MAX_BYTES/1024} KB.`,413);const image=pngSize(data)??jpegSize(data)??webpSize(data);if(!image)throw new AssetError('unsupported_image','Choose a non-animated PNG, JPEG, or WebP image.');if(!image.width||!image.height||image.width>ASSET_MAX_DIMENSION||image.height>ASSET_MAX_DIMENSION||image.width*image.height>ASSET_MAX_PIXELS)throw new AssetError('image_dimensions',`Choose an image no larger than ${ASSET_MAX_DIMENSION} px per side and ${ASSET_MAX_PIXELS/1_000_000} megapixels.`);return image}
// A shared library that sends a malformed label must not break the import; fall back to
// a safe default rather than failing the whole shared preview.
function importedLabel(raw:string|null,fallback:string,label:string,max:number){if(raw)try{return boundedText(raw,label,max)}catch{/* fall through to the default label */}return fallback}
function boundedText(value:string,label:string,max:number){let decoded:string;try{decoded=decodeURIComponent(value)}catch{throw new AssetError('invalid_input',`${label} is invalid`)}if(!decoded.trim()||decoded.length>max)throw new AssetError('invalid_input',`${label} must be 1-${max} characters`);return decoded.trim()}
export async function createAsset(data:Uint8Array,headers:Headers,actor:string,repository:AssetRepository=defaultAssetRepository()){const name=boundedText(headers.get('x-asset-name')??'','Name',160),altText=boundedText(headers.get('x-asset-alt')??'','Alternative text',240),image=inspectAssetImage(data),hash=createHash('sha256').update(data).digest('hex'),id=`asset_${hash}`,existing=await repository.get(id);if(existing)return existing;if(await repository.count()>=ASSET_MAX_ITEMS)throw new AssetError('asset_limit',`This workspace has reached its ${ASSET_MAX_ITEMS}-asset limit, which includes archived artwork. Archived artwork still counts because its bytes stay stored for historical outputs, and archive cleanup does not remove published history.`,409);const now=Date.now(),record:AssetRecord={id,name,altText,mimeType:image.mimeType,bytes:data.byteLength,width:image.width,height:image.height,version:1,archived:false,published:false,createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor,privatePreviewUrl:`/api/assets/${id}/preview`,data};if(!await repository.insert(record))return (await repository.get(id))!;return record}
export function assetMetadata(record:AssetRecord):AssetMetadata{const metadata=clone(record) as AssetMetadata&{data?:Uint8Array};delete metadata.data;return metadata}
export async function markAssetPublished(connection:AssetQueryable,id:string,now=Date.now()){if(!/^asset_[a-f0-9]{64}$/.test(id))throw new AssetError('invalid_asset','Asset ID is invalid');const result=await connection.query('UPDATE workspace_assets SET published_at=COALESCE(published_at,$2) WHERE id=$1 AND archived=false RETURNING id',[id,now]);return Boolean(result.rowCount)}
export function cueAssetId(cue:{presentation?:{imageAssetId?:string}}){const id=cue.presentation?.imageAssetId;if(id!==undefined&&!/^asset_[a-f0-9]{64}$/.test(id))throw new AssetError('invalid_asset','Cue references an invalid asset');return id}
export async function markCueAssetPublished(connection:AssetQueryable,cue:{presentation?:{imageAssetId?:string}},now=Date.now()){const id=cueAssetId(cue);if(id&&!await markAssetPublished(connection,id,now))throw new AssetError('asset_unavailable','Selected artwork is unavailable or archived',409)}
export async function cueAssetUrl(cue:{presentation?:{imageAssetId?:string}},audience:'preview'|'published',repository:AssetRepository=defaultAssetRepository()){const id=cueAssetId(cue);if(!id)return undefined;const asset=await repository.get(id);if(!asset||(audience==='published'&&!asset.published))throw new AssetError('asset_unavailable','Selected artwork is unavailable',409);return audience==='preview'?asset.privatePreviewUrl:(asset.publicUrl??`/api/assets/${encodeURIComponent(id)}/content`)}

type AssetImportEnvironment=Partial<Pick<NodeJS.ProcessEnv,'WORKSPACE_ID'|'CRC_SHARED_LIBRARY_URL'|'SHARED_LIBRARY_IMPORT_KEY'|'CONTROL_KEY'|'OUTPUT_KEY'|'ACCESS_BOOTSTRAP_KEY'>>;
export async function importSharedAsset(id:string,actor:string,repository:AssetRepository=defaultAssetRepository(),env:AssetImportEnvironment=process.env as AssetImportEnvironment,fetcher:typeof fetch=fetch){
 if(env.WORKSPACE_ID?.trim().toLowerCase()!=='temple-bnai-israel-kalamazoo'||!/^asset_[a-f0-9]{64}$/.test(id))throw new AssetError('asset_import_denied','Shared asset import is unavailable',403);const key=env.SHARED_LIBRARY_IMPORT_KEY;if(!key||key.length<32||[env.CONTROL_KEY,env.OUTPUT_KEY,env.ACCESS_BOOTSTRAP_KEY].some(secret=>secret&&secret===key))throw new AssetError('asset_import_unavailable','Shared asset import is not configured',503);let url:URL;try{url=new URL(env.CRC_SHARED_LIBRARY_URL??'');if(url.protocol!=='https:'||url.username||url.password||url.hash||!url.pathname.endsWith('/api/shared-library'))throw new Error();url.pathname=`${url.pathname}/assets/${id}`}catch{throw new AssetError('asset_import_unavailable','Shared asset import is not configured',503)}
 const existing=await repository.get(id);if(existing)return existing;
 const response=await fetcher(url,{headers:{Authorization:`Bearer ${key}`},cache:'no-store',redirect:'error',signal:AbortSignal.timeout(7000)});if(!response.ok)throw new AssetError('asset_import_unavailable','Shared artwork is temporarily unavailable',503);const declared=Number(response.headers.get('content-length')??0);if(declared>ASSET_MAX_BYTES)throw new AssetError('asset_import_invalid','Shared artwork exceeds the size limit',502);const reader=response.body?.getReader();if(!reader)throw new AssetError('asset_import_invalid','Shared artwork has no content',502);const chunks:Uint8Array[]=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>ASSET_MAX_BYTES){await reader.cancel();throw new AssetError('asset_import_invalid','Shared artwork exceeds the size limit',502)}chunks.push(value)}const data=new Uint8Array(size);let offset=0;for(const chunk of chunks){data.set(chunk,offset);offset+=chunk.length}if(`asset_${createHash('sha256').update(data).digest('hex')}`!==id)throw new AssetError('asset_import_invalid','Shared artwork failed integrity verification',502);const headers=new Headers({'x-asset-name':encodeURIComponent(importedLabel(response.headers.get('x-asset-name'),id,'Name',160)),'x-asset-alt':encodeURIComponent(importedLabel(response.headers.get('x-asset-alt'),'Congregation artwork','Alternative text',240))});return createAsset(data,headers,actor,repository)
}
