import type {Cue} from './player';
const aliases:Record<string,string[]>= {kaddish:['kadish'],barchu:['barechu','bar chu'],shma:['shema'],'v ahavta':['veahavta','vahafta'],'mi chamocha':['mi khamocha'],'oseh shalom':['ose shalom'],'ahava rabbah':['ahavah rabah']};
export function normalizeCueSearch(value:string){return value.normalize('NFD').replace(/[\u0591-\u05c7\u0300-\u036f]/g,'').replace(/[’'`״׳\-–—.,:;!?()[\]{}]/g,' ').toLocaleLowerCase().replace(/\s+/g,' ').trim()}
/** The one operator-facing cue label. The defective "(ncomplete)" spelling was renamed in the catalog itself (T4), so only the correctly spelled "(incomplete)" marker still needs mapping to the settled word "(Partial)". Names that already read "(Partial)" pass through unchanged. */
export function friendlyCueName(name:string){return name.replace(/\s*\(incomplete\)\s*$/i,' (Partial)')}
function distance(a:string,b:string){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let previous=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,previous+(a[i-1]===b[j-1]?0:1));previous=old}}return row[b.length]}
function searchText(cue:Cue){const name=normalizeCueSearch(friendlyCueName(cue.name)),extra=Object.entries(aliases).filter(([key])=>name.includes(key)).flatMap(([,values])=>values);return normalizeCueSearch([name,cue.id,...extra,...Object.values(cue.texts),...(cue.contentRows??[]).flatMap(row=>[row.he,row.tr,row.en])].join(' '))}
export function cueSearchScore(cue:Cue,query:string){const needle=normalizeCueSearch(query);if(!needle)return 1;const text=searchText(cue),name=normalizeCueSearch(friendlyCueName(cue.name));if(name===needle)return 100;if(name.startsWith(needle))return 80;if(text.includes(needle))return 60;const words=text.split(' '),terms=needle.split(' ');if(terms.every(term=>words.some(word=>word.startsWith(term))))return 45;const fuzzy=terms.every(term=>term.length>=4&&words.some(word=>Math.abs(word.length-term.length)<=2&&distance(word,term)<=Math.max(1,Math.floor(term.length/4))));return fuzzy?25:0}
export function searchCues(cues:Cue[],query:string){return cues.map((cue,index)=>({cue,index,score:cueSearchScore(cue,query)})).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.index-b.index).map(item=>item.cue)}
