import {OAuthError,OAuthErrorCode,type AuthInfo,type OAuthTokenVerifier} from '@modelcontextprotocol/server';
import {db} from './database';
import {AUTHORING_SCOPE,AUTH_REQUEST_TTL_MS,CODE_TTL_MS,REFRESH_TOKEN_TTL_MS,TOKEN_TTL_MS,hashOpaque,opaque,pkceChallenge,validPkceVerifier} from './oauth-core';

type ClientRow={client_id_hash:string;redirect_uris:string[];client_name:string};
type AuthRequestRow={client_id_hash:string;redirect_uri:string;code_challenge:string;scope:string;resource:string;state:string|null};
type CodeRow=AuthRequestRow&{actor:string};

export async function rateLimit(bucket:string,identity:string,limit:number,windowMs:number){
 const key=hashOpaque(`${bucket}\0${identity}`),now=Date.now(),cutoff=now-windowMs;
 const result=await db.query(`INSERT INTO oauth_rate_limits(key_hash,window_start,count) VALUES($1,$2,1)
 ON CONFLICT(key_hash) DO UPDATE SET window_start=CASE WHEN oauth_rate_limits.window_start<$3 THEN $2 ELSE oauth_rate_limits.window_start END,
 count=CASE WHEN oauth_rate_limits.window_start<$3 THEN 1 ELSE oauth_rate_limits.count+1 END RETURNING count`,[key,now,cutoff]);
 return Number(result.rows[0].count)<=limit;
}
export async function registerClient(redirectUris:string[],clientName:string){const clientId=opaque('crc_client_');await db.query('INSERT INTO oauth_clients(client_id_hash,redirect_uris,client_name,created) VALUES($1,$2,$3,$4)',[hashOpaque(clientId),JSON.stringify(redirectUris),clientName,Date.now()]);return clientId}
export async function getClient(clientId:string){const result=await db.query<ClientRow>('SELECT client_id_hash,redirect_uris,client_name FROM oauth_clients WHERE client_id_hash=$1',[hashOpaque(clientId)]);return result.rows[0]??null}
export async function createAuthorizationRequest(input:{clientId:string;redirectUri:string;codeChallenge:string;scope:string;resource:string;state:string|null}){const id=opaque('crc_req_');await db.query('INSERT INTO oauth_authorization_requests(request_hash,client_id_hash,redirect_uri,code_challenge,scope,resource,state,expires) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[hashOpaque(id),hashOpaque(input.clientId),input.redirectUri,input.codeChallenge,input.scope,input.resource,input.state,Date.now()+AUTH_REQUEST_TTL_MS]);return id}
export async function peekAuthorizationRequest(id:string){const result=await db.query<AuthRequestRow>('SELECT client_id_hash,redirect_uri,code_challenge,scope,resource,state FROM oauth_authorization_requests WHERE request_hash=$1 AND expires>$2',[hashOpaque(id),Date.now()]);return result.rows[0]??null}
export async function consumeAuthorizationRequest(id:string){const result=await db.query<AuthRequestRow>('DELETE FROM oauth_authorization_requests WHERE request_hash=$1 AND expires>$2 RETURNING client_id_hash,redirect_uri,code_challenge,scope,resource,state',[hashOpaque(id),Date.now()]);return result.rows[0]??null}
export async function issueAuthorizationCode(request:AuthRequestRow){const code=opaque('crc_code_');const actor=`mcp:${request.client_id_hash.slice(0,16)}`;await db.query('INSERT INTO oauth_codes(code_hash,client_id_hash,redirect_uri,code_challenge,scope,resource,actor,expires) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[hashOpaque(code),request.client_id_hash,request.redirect_uri,request.code_challenge,request.scope,request.resource,actor,Date.now()+CODE_TTL_MS]);return code}
export async function exchangeAuthorizationCode(input:{code:string;clientId:string;redirectUri:string;verifier:string;resource:string}){
 if(!validPkceVerifier(input.verifier))throw Error('invalid_grant');const client=await db.connect();
 try{await client.query('BEGIN');const result=await client.query<CodeRow>('SELECT client_id_hash,redirect_uri,code_challenge,scope,resource,actor FROM oauth_codes WHERE code_hash=$1 AND used_at IS NULL AND expires>$2 FOR UPDATE',[hashOpaque(input.code),Date.now()]);const row=result.rows[0];
  if(!row||row.client_id_hash!==hashOpaque(input.clientId)||row.redirect_uri!==input.redirectUri||row.resource!==input.resource||row.code_challenge!==pkceChallenge(input.verifier))throw Error('invalid_grant');
  await client.query('UPDATE oauth_codes SET used_at=$2 WHERE code_hash=$1',[hashOpaque(input.code),Date.now()]);const token=opaque('crc_at_'),refreshToken=opaque('crc_rt_'),expires=Date.now()+TOKEN_TTL_MS,refreshExpires=Date.now()+REFRESH_TOKEN_TTL_MS,familyHash=hashOpaque(opaque('crc_family_'));await client.query('INSERT INTO oauth_tokens(token_hash,family_hash,client_id_hash,scope,resource,actor,expires) VALUES($1,$2,$3,$4,$5,$6,$7)',[hashOpaque(token),familyHash,row.client_id_hash,row.scope,row.resource,row.actor,expires]);await client.query('INSERT INTO oauth_refresh_tokens(token_hash,family_hash,client_id_hash,scope,resource,actor,expires) VALUES($1,$2,$3,$4,$5,$6,$7)',[hashOpaque(refreshToken),familyHash,row.client_id_hash,row.scope,row.resource,row.actor,refreshExpires]);await client.query('COMMIT');return {token,refreshToken,expires,scope:row.scope};
 }catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}
}
export async function exchangeRefreshToken(input:{refreshToken:string;clientId:string;resource:string}){
 const client=await db.connect();const tokenHash=hashOpaque(input.refreshToken);let transactionOpen=false;try{await client.query('BEGIN');transactionOpen=true;const result=await client.query<{family_hash:string;client_id_hash:string;scope:string;resource:string;actor:string}>('SELECT family_hash,client_id_hash,scope,resource,actor FROM oauth_refresh_tokens WHERE token_hash=$1 AND expires>$2 FOR UPDATE',[tokenHash,Date.now()]);const row=result.rows[0];
  if(!row||row.client_id_hash!==hashOpaque(input.clientId)||row.resource!==input.resource)throw Error('invalid_grant');
  const used=await client.query<{used_at:number|null;revoked_at:number|null}>('SELECT used_at,revoked_at FROM oauth_refresh_tokens WHERE token_hash=$1',[tokenHash]);if(used.rows[0]?.used_at||used.rows[0]?.revoked_at){const revokedAt=Date.now();await client.query('UPDATE oauth_refresh_tokens SET revoked_at=$2 WHERE family_hash=$1 AND revoked_at IS NULL',[row.family_hash,revokedAt]);await client.query('UPDATE oauth_tokens SET revoked_at=$2 WHERE family_hash=$1 AND revoked_at IS NULL',[row.family_hash,revokedAt]);await client.query('COMMIT');transactionOpen=false;throw Error('invalid_grant')}
  await client.query('UPDATE oauth_refresh_tokens SET used_at=$2 WHERE token_hash=$1',[tokenHash,Date.now()]);const token=opaque('crc_at_'),refreshToken=opaque('crc_rt_'),expires=Date.now()+TOKEN_TTL_MS;await client.query('INSERT INTO oauth_tokens(token_hash,family_hash,client_id_hash,scope,resource,actor,expires) VALUES($1,$2,$3,$4,$5,$6,$7)',[hashOpaque(token),row.family_hash,row.client_id_hash,row.scope,row.resource,row.actor,expires]);await client.query('INSERT INTO oauth_refresh_tokens(token_hash,family_hash,client_id_hash,scope,resource,actor,expires) VALUES($1,$2,$3,$4,$5,$6,$7)',[hashOpaque(refreshToken),row.family_hash,row.client_id_hash,row.scope,row.resource,row.actor,Date.now()+REFRESH_TOKEN_TTL_MS]);await client.query('COMMIT');transactionOpen=false;return {token,refreshToken,expires,scope:row.scope};
 }catch(error){if(transactionOpen)try{await client.query('ROLLBACK')}catch{}throw error}finally{client.release()}
}
export async function revokeToken(raw:string,clientId:string){const hashed=hashOpaque(raw),clientHash=hashOpaque(clientId),client=await db.connect();try{await client.query('BEGIN');const refresh=await client.query<{family_hash:string}>('SELECT family_hash FROM oauth_refresh_tokens WHERE token_hash=$1 AND client_id_hash=$2 FOR UPDATE',[hashed,clientHash]);if(refresh.rows[0]){const revokedAt=Date.now();await client.query('UPDATE oauth_refresh_tokens SET revoked_at=$2 WHERE family_hash=$1 AND revoked_at IS NULL',[refresh.rows[0].family_hash,revokedAt]);await client.query('UPDATE oauth_tokens SET revoked_at=$2 WHERE family_hash=$1 AND revoked_at IS NULL',[refresh.rows[0].family_hash,revokedAt])}else await client.query('UPDATE oauth_tokens SET revoked_at=$3 WHERE token_hash=$1 AND client_id_hash=$2',[hashed,clientHash,Date.now()]);await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
export const tokenVerifier:OAuthTokenVerifier={async verifyAccessToken(token:string){const result=await db.query<{client_id_hash:string;scope:string;resource:string;actor:string;expires:number}>('SELECT client_id_hash,scope,resource,actor,expires FROM oauth_tokens WHERE token_hash=$1 AND revoked_at IS NULL AND expires>$2',[hashOpaque(token),Date.now()]);const row=result.rows[0];if(!row||row.scope!==AUTHORING_SCOPE)throw new OAuthError(OAuthErrorCode.InvalidToken,'Invalid or expired token');return {token,clientId:row.client_id_hash,scopes:row.scope.split(' '),expiresAt:Math.floor(Number(row.expires)/1000),resource:new URL(row.resource),extra:{actor:row.actor}} satisfies AuthInfo}};
