import {branding} from './branding';
import {acceptsRevision,effectFrames,easingFor,incomingStillDesired,tracksFor,type AnimationDirection,type AnimationTrack,type PlayerState} from './player-motion';
export type CueTemplate={family?:'lower-third'|'panel-left'|'panel-right';version?:string;translatePx?:number};
export type Cue={id:string;name:string;layout:string;texts:Record<string,string>;animations:AnimationTrack[];duration:Record<string,number>;template?:CueTemplate};
export class Player{
 root:HTMLElement; cues:Cue[]; current:Cue|null=null; desired:PlayerState={cue:null,revision:0,mode:'animate'};revision=0;busy=false;generation=0;phase='settled';
 constructor(root:HTMLElement,cues:Cue[]){this.root=root;this.cues=cues}
 set(state:PlayerState){if(!acceptsRevision(state,this.desired))return;this.desired=state;if(state.mode==='cut'){this.generation++;this.root.getAnimations({subtree:true}).forEach(a=>a.cancel());this.root.replaceChildren();this.current=null;this.revision=state.revision;this.phase='settled';this.busy=false;return}void this.drain()}
 dispose(){this.generation++;this.root.getAnimations({subtree:true}).forEach(a=>a.cancel());this.root.replaceChildren()}
 render(c:Cue){const box=document.createElement('div');box.className=`overlay ${c.layout}`;
const add=(classes:string,text:string,name:string)=>{const el=document.createElement(classes==='logo'?'img':'div');el.className=`part ${classes}`;el.dataset.element=name;if(el instanceof HTMLImageElement){el.src=branding.logo;el.alt='CRC'}else el.textContent=text;box.appendChild(el);return el};
add('base','','baseMain');add('titlebar','','baseTitle');const grad=add('titlebar titlegrad','','baseTitleGrad');grad.style.background=`linear-gradient(90deg,${branding.titleShade},${branding.titleColor})`;add('accent','','accentLineBottom');if(c.texts.textTitle)add('title',c.texts.textTitle,'textTitle');if(c.texts.accentTextTitle)add('title title-accent',c.texts.accentTextTitle,'accentTextTitle');if(c.texts.textMain)add('prayer combined',c.texts.textMain,'textMain');else{if(c.texts.textMainEng)add('prayer english',c.texts.textMainEng,'textMainEng');if(c.texts.textMainheb)add('prayer hebrew',c.texts.textMainheb,'textMainheb')}add('logo','','Image');this.root.replaceChildren(box);return box}
 async animate(box:HTMLElement,c:Cue,direction:AnimationDirection){const duration=c.duration[direction]||.5;const translatePx=c.template?.translatePx||48;const elements=Array.from(box.querySelectorAll<HTMLElement>('[data-element]'));await Promise.all(elements.flatMap(el=>tracksFor(el.dataset.element||'',direction,c.animations).map(track=>{const range=track.keyframes?.length===2?track.keyframes:[0,duration];return el.animate(effectFrames(track.effect,direction,translatePx),{duration:Math.max(1,(range[1]-range[0])*1000),delay:range[0]*1000,fill:'both',easing:easingFor(track.effect)}).finished})))}
 async drain(){if(this.busy)return;this.busy=true;const g=this.generation;try{while(g===this.generation){if((this.current?.id??null)===this.desired.cue){this.revision=this.desired.revision;this.phase='settled';break}this.phase='transition';if(this.current&&this.root.firstElementChild){await this.animate(this.root.firstElementChild as HTMLElement,this.current,'Out');if(g!==this.generation)return;this.root.replaceChildren();this.current=null}if(this.desired.cue){const cue=this.cues.find(c=>c.id===this.desired.cue);if(!cue)throw Error('Unknown cue');const box=this.render(cue);await this.animate(box,cue,'In');if(g!==this.generation)return;if(!incomingStillDesired(cue.id,this.desired)){this.root.replaceChildren();continue}this.current=cue}}}catch{if(g===this.generation)this.phase='error'}finally{if(g===this.generation)this.busy=false}}
}


