import {branding} from './branding';
export type Cue={id:string;name:string;layout:string;texts:Record<string,string>;animations:any[];duration:Record<string,number>};
export class Player{
 root:HTMLElement; cues:Cue[]; current:Cue|null=null; desired:{cue:string|null;revision:number;mode:string}={cue:null,revision:0,mode:'animate'};revision=0;busy=false;generation=0;phase='settled';
 constructor(root:HTMLElement,cues:Cue[]){this.root=root;this.cues=cues}
 set(state:{cue:string|null;revision:number;mode:string}){if(state.revision<this.desired.revision)return;this.desired=state;if(state.mode==='cut'){this.generation++;this.root.getAnimations({subtree:true}).forEach(a=>a.cancel());this.root.replaceChildren();this.current=null;this.revision=state.revision;this.phase='settled';this.busy=false;return}void this.drain()}
 dispose(){this.generation++;this.root.getAnimations({subtree:true}).forEach(a=>a.cancel());this.root.replaceChildren()}
 render(c:Cue){const box=document.createElement('div');box.className=`overlay ${c.layout}`;
const add=(classes:string,text:string,name:string)=>{const el=document.createElement(classes==='logo'?'img':'div');el.className=`part ${classes}`;el.dataset.element=name;if(el instanceof HTMLImageElement){el.src=branding.logo;el.alt='CRC'}else el.textContent=text;box.appendChild(el);return el};
add('base','','baseMain');const bar=add('titlebar','','baseTitle');bar.style.background=`linear-gradient(90deg,${branding.titleShade},${branding.titleColor})`;add('accent','','accentLineBottom');add('title',c.texts.textTitle,'textTitle');add('prayer',c.texts.textMain||c.texts.textMainEng,'textMain');if(c.texts.textMainheb)add('prayer hebrew',c.texts.textMainheb,'textMainheb');add('logo','','Image');this.root.replaceChildren(box);return box}
 async animate(box:HTMLElement,c:Cue,direction:string){const duration=c.duration[direction]||.5;await Promise.all(Array.from(box.children).map(el=>{const a=c.animations.find(a=>a.element===(el as HTMLElement).dataset.element&&a.direction===direction);const range=a?.keyframes||[0,duration];const scale=a?.effect?.effect==='scale';const hidden=scale?{transform:a?.effect?.property==='xAndY'?'scale(0)':'scaleX(0)'}:{opacity:0};const visible=scale?{transform:'scale(1)'}:{opacity:1};return el.animate(direction==='In'?[hidden,visible]:[visible,hidden],{duration:Math.max(1,(range[1]-range[0])*1000),delay:range[0]*1000,fill:'both',easing:direction==='In'?'cubic-bezier(.2,.8,.3,1)':'cubic-bezier(.5,0,.8,.3)'}).finished}))}
 async drain(){if(this.busy)return;this.busy=true;const g=this.generation;try{while(g===this.generation){if((this.current?.id??null)===this.desired.cue){this.revision=this.desired.revision;this.phase='settled';break}this.phase='transition';if(this.current&&this.root.firstElementChild){await this.animate(this.root.firstElementChild as HTMLElement,this.current,'Out');if(g!==this.generation)return;this.root.replaceChildren();this.current=null}if(this.desired.cue){const cue=this.cues.find(c=>c.id===this.desired.cue);if(!cue)throw Error('Unknown cue');await this.animate(this.render(cue),cue,'In');if(g!==this.generation)return;this.current=cue}}}catch{if(g===this.generation)this.phase='error'}finally{if(g===this.generation)this.busy=false}}
}


