export const GUIDE_VERSION='2026.09.1';
export const guideSections=[
 {id:'before-service',title:'Before a service',summary:'Confirm the system while the graphics input is off air.',steps:['Open Companion and confirm the congregation’s Overlays connection says OK.','Open the graphics browser input and check Health for a connected output.','Inspect checks a graphic only in the browser. For the real signal check, keep the graphics input off air, then use Show on one short graphic and one long graphic, followed by Animate Out and Clear Now. Confirm the graphics input and composite monitor after each action.','Keep the existing Singular input available until the physical rehearsal has passed.']},
 {id:'during-service',title:'During a service',summary:'Use the controls operators already know.',steps:['Use the congregation-labeled Companion pages or Live control to select a graphic.','Preview before Show whenever the service pace allows.','Use Animate Out for a normal exit. Use Clear Now only when the picture must disappear immediately.','If Library synchronization says pending, use the last known live graphics and resolve publishing after the service.']},
 {id:'fallback',title:'Return to Singular',summary:'A calm fallback when a new graphics path is not ready.',steps:['Take the Overlays browser input off air.','Use the unchanged Singular browser input and its existing Companion pages.','Do not troubleshoot accounts, publishing, or provider settings during the service.','Record what failed and the time, then check Health after the service.']},
 {id:'after-service',title:'After a service',summary:'Leave the next operator a known state.',steps:['Clear the graphic and confirm the output is empty.','Record any unavailable, pending, or fallback result in Services while the context is fresh.','Publish library edits only after reviewing their exact preview.','Once a month, review provider usage and the latest recovery package with an administrator.']},
 {id:'accounts',title:'Accounts and handoff',summary:'Give each person their own access.',steps:['An administrator opens Account and creates a one-use invitation for the person’s exact email address.','Choose Operator for live use, Editor for library work, or Administrator only for people who manage access.','The recipient opens the link within 24 hours and sets a password.','Disable an account promptly when a person no longer needs access. Keep at least one administrator enabled.']},
 {id:'recovery',title:'Backup and restore rehearsal',summary:'Prove recovery without touching the live service.',steps:['An administrator runs the recovery export after material changes and before a major service. Store the package in restricted congregation storage.','Run the bundle verifier before accepting the backup. It confirms the version and every file checksum.','Restore only into a separate rehearsal database. The restore tool refuses production and refuses the live database URL.','Open the rehearsal catalog, inspect at least one custom graphic and one source-linked graphic, and record the date and result. Never include passwords, sessions, invitation links, relay secrets, or output URLs in a bundle.']},
] as const;
