import {createHash,randomUUID} from 'node:crypto';
import {AuthoringError,baselineCues,parseEditable,sourcePack,sourcePinFor,sourceReferences,sourceSnapshotsFor,type AuthoringSource,type Draft,type DraftContent,type EditableDraft,type LocalVariantContent,type SourceBlock,type VariantChannel} from './authoring-model';
import {authoringRepository,authoringRepositoryMode,type AuthoringRepository} from './authoring';

export type SourceChangeStatus='pending'|'deferred'|'rejected'|'accepted';
export type SourceTextChange={blockId:string;blockIndex:number;channel:VariantChannel;role:string;priorText:string|null;proposedText:string|null;pairedBlockIds:string[];paginationMayChange:boolean};
export type SourceChangeRecord={
 id:string;version:number;status:SourceChangeStatus;comparison:'exact'|'unavailable';workspaceId:string;sourceId:string;sourceName:string;book:string;service:string;
 fromFeedSha256:string;toFeedSha256:string;fromUnitSha256:string;toUnitSha256:string;detectedAt:number;detectedBy:string;
 affected:{draftId:string;draftVersion:number;draftName:string;published:boolean;layout:string;draftSetId:string|null;sharedFrom:'crc'|'workspace';presentation:Draft['presentation'];serviceCollections:Array<{id:string;name:string;service:string;archived:boolean}>};
 changes:SourceTextChange[];blockedReason?:string;decision?:{kind:Exclude<SourceChangeStatus,'pending'>;reason:string|null;actor:string;at:number;createdDraftId:string|null};
 priorSource?:AuthoringSource;proposedSource?:AuthoringSource;priorDraft?:Draft;
};
export type SourceChangeSummary=Omit<SourceChangeRecord,'priorSource'|'proposedSource'|'priorDraft'|'changes'> & {changeCount:number;paginationMayChange:boolean};

export interface SourceReviewRepository{
 upsert(records:SourceChangeRecord[]):Promise<void>;list():Promise<SourceChangeRecord[]>;get(id:string):Promise<SourceChangeRecord|null>;
 decide(id:string,expectedVersion:number,decision:SourceChangeRecord['decision'],draft:Draft|null):Promise<{record:SourceChangeRecord;draft:Draft|null}>;
}

const clone=<T>(value:T):T=>structuredClone(value);
const role=(block:SourceBlock|undefined,channel:VariantChannel)=>channel==='he'?'Hebrew':channel==='tr'?'Transliteration':block?.role==='original'?'Original English':block?.englishRole==='unclassified'||!block?.englishRole?'English text':block.englishRole.split('-').map(word=>word[0].toUpperCase()+word.slice(1)).join(' ');
const recordId=(draftId:string,sourceId:string,from:string,to:string)=>createHash('sha256').update(JSON.stringify([draftId,sourceId,from,to])).digest('hex');
const publicRecord=(record:SourceChangeRecord)=>{const safe=clone(record);delete safe.priorSource;delete safe.proposedSource;delete safe.priorDraft;return safe};
const summary=(record:SourceChangeRecord):SourceChangeSummary=>{const safe=publicRecord(record),changes=safe.changes;delete (safe as Partial<SourceChangeRecord>).changes;return {...safe,changeCount:changes.length,paginationMayChange:changes.some(change=>change.paginationMayChange)} as SourceChangeSummary};
function updatedVariantContent(content:DraftContent,sourceId:string,proposed:AuthoringSource):DraftContent{
 if(content.mode!=='local-variant')return clone(content);
 const overrides=content.overrides.map(override=>override.sourceId!==sourceId?clone(override):{...clone(override),sourceText:String(proposed.blocks.find(block=>block.id===override.blockId)?.[override.channel]??'')});
 return {...clone(content),overrides} satisfies LocalVariantContent;
}

export class MemorySourceReviewRepository implements SourceReviewRepository{
 private records=new Map<string,SourceChangeRecord>();constructor(private drafts:AuthoringRepository){}
 async upsert(records:SourceChangeRecord[]){for(const record of records)if(!this.records.has(record.id))this.records.set(record.id,clone(record))}
 async list(){return [...this.records.values()].map(clone).sort((a,b)=>b.detectedAt-a.detectedAt)}
 async get(id:string){const value=this.records.get(id);return value?clone(value):null}
 async decide(id:string,expectedVersion:number,decision:SourceChangeRecord['decision'],draft:Draft|null){const current=this.records.get(id);if(!current||current.version!==expectedVersion)throw new AuthoringError('conflict','This source review changed elsewhere. Refresh and try again.',409);if(current.status==='accepted'||current.status==='rejected')throw new AuthoringError('review_closed','This source review is already closed',409);if(draft)await this.drafts.insertDraft(draft);const next={...current,version:current.version+1,status:decision!.kind,decision:clone(decision!)};this.records.set(id,next);return {record:clone(next),draft:clone(draft)}}
}

export class PgSourceReviewRepository implements SourceReviewRepository{
 private async db(){return (await import('./database')).db}
 async upsert(records:SourceChangeRecord[]){const db=await this.db();for(const record of records)await db.query('INSERT INTO source_change_reviews(id,document,version,status,detected_at,updated_at) VALUES($1,$2,1,$3,$4,$4) ON CONFLICT(id) DO NOTHING',[record.id,record,record.status,record.detectedAt])}
 async list(){return (await (await this.db()).query('SELECT document FROM source_change_reviews ORDER BY updated_at DESC')).rows.map((row:{document:SourceChangeRecord})=>row.document)}
 async get(id:string){return (await (await this.db()).query('SELECT document FROM source_change_reviews WHERE id=$1',[id])).rows[0]?.document??null}
 async decide(id:string,expectedVersion:number,decision:SourceChangeRecord['decision'],draft:Draft|null){const db=await this.db(),client=await db.connect();try{await client.query('BEGIN');const row=await client.query('SELECT document FROM source_change_reviews WHERE id=$1 AND version=$2 FOR UPDATE',[id,expectedVersion]);const current=row.rows[0]?.document as SourceChangeRecord|undefined;if(!current)throw new AuthoringError('conflict','This source review changed elsewhere. Refresh and try again.',409);if(current.status==='accepted'||current.status==='rejected')throw new AuthoringError('review_closed','This source review is already closed',409);if(draft)await client.query('INSERT INTO authoring_drafts(id,document,version,created_at,updated_at,created_by,updated_by) VALUES($1,$2,1,$3,$3,$4,$4)',[draft.id,draft,draft.createdAt,draft.createdBy]);const next:SourceChangeRecord={...current,version:expectedVersion+1,status:decision!.kind,decision:clone(decision!)};await client.query('UPDATE source_change_reviews SET document=$2,version=$3,status=$4,updated_at=$5 WHERE id=$1',[id,next,next.version,next.status,decision!.at]);await client.query('COMMIT');return {record:next,draft}}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
}

function detectForDraft(draft:Draft,actor:string,now:number){
 const results:SourceChangeRecord[]=[];if(draft.content.mode==='custom')return results;const references=sourceReferences(draft.content,draft.sourceSnapshots);const sourceIds=[...new Set(references.map(reference=>reference.sourceId))];
 for(const sourceId of sourceIds){const proposed=sourcePack.sources.find(source=>source.id===sourceId),prior=draft.sourceSnapshots?.find(source=>source.id===sourceId),fromUnit=draft.sourcePin.unitSha256[sourceId];if(!fromUnit)continue;const toUnit=proposed?.unitSha256??'missing';if(fromUnit===toUnit)continue;const reference=proposed??prior;const base={id:recordId(draft.id,sourceId,fromUnit,toUnit),version:1,status:'pending' as const,workspaceId:process.env.WORKSPACE_ID??'crc',sourceId,sourceName:reference?.name??sourceId,book:reference?.book??'',service:reference?.service??'',fromFeedSha256:draft.sourcePin.feedSha256,toFeedSha256:sourcePack.authority.feedSha256,fromUnitSha256:fromUnit,toUnitSha256:toUnit,detectedAt:now,detectedBy:actor,affected:{draftId:draft.id,draftVersion:draft.version,draftName:draft.name,published:draft.activeRevision!==null,layout:draft.layout,draftSetId:draft.draftSetId??null,sharedFrom:draft.sharedFrom?'crc' as const:'workspace' as const,presentation:clone(draft.presentation),serviceCollections:[]}};
  if(!prior){results.push({...base,comparison:'unavailable',changes:[],blockedReason:'The historical source snapshot predates retained source history. Exact comparison and acceptance are unavailable.'});continue}
  const changes:SourceTextChange[]=[];for(const selected of references.filter(item=>item.sourceId===sourceId)){const oldBlock=prior.blocks.find(block=>block.id===selected.blockId),newBlock=proposed?.blocks.find(block=>block.id===selected.blockId);for(const channel of ['he','tr','en'] as VariantChannel[]){const priorText=oldBlock?.[channel]??null,proposedText=newBlock?.[channel]??null;if(priorText===proposedText)continue;if(priorText===null&&proposedText===null)continue;changes.push({blockId:selected.blockId,blockIndex:oldBlock?.index??newBlock?.index??0,channel,role:role(newBlock??oldBlock,channel),priorText,proposedText,pairedBlockIds:clone(newBlock?.pairedBlockIds??newBlock?.parallelBlockIds??oldBlock?.pairedBlockIds??oldBlock?.parallelBlockIds??[]),paginationMayChange:true})}}
  if(!proposed)results.push({...base,comparison:'exact',changes,priorSource:clone(prior),blockedReason:'This selected source is no longer available in the proposed revision. Choose a replacement manually after review.'});
  else if(changes.length)results.push({...base,comparison:'exact',changes,priorSource:clone(prior),proposedSource:clone(proposed),...(changes.some(change=>change.proposedText===null)?{blockedReason:'One or more selected source blocks or channels were removed. Create a replacement manually after review.'}:{})});
 }
 return results;
}
function baselineCoverage(existingIds:Set<string>){const candidates=baselineCues.filter(cue=>!cue.hidden&&!existingIds.has(cue.id)),verifiable=candidates.filter(cue=>Boolean(cue.authoring?.copySpec?.sourceSnapshots?.length));return {total:candidates.length,verifiable:verifiable.length,unverifiable:candidates.length-verifiable.length,message:candidates.length===verifiable.length?'Every graphic has saved source text.':`${candidates.length-verifiable.length} older graphic${candidates.length-verifiable.length===1?'':'s'} have no saved source text. Open one to compare it.`}}
function baselineDrafts(existingIds:Set<string>,now:number){return baselineCues.filter(cue=>!cue.hidden&&!existingIds.has(cue.id)&&cue.authoring?.copySpec?.sourceSnapshots?.length).map(cue=>{const spec=cue.authoring.copySpec!,{sourcePin,sourceSnapshots,...editable}=spec;return {...clone(editable),id:cue.id,version:cue.authoring.draftVersion||1,sourcePin:clone(sourcePin),sourceSnapshots:clone(sourceSnapshots),activeRevision:1,activeDraftVersion:cue.authoring.draftVersion||1,createdAt:now,updatedAt:now,createdBy:'baseline',updatedBy:'baseline'} satisfies Draft})}

type CollectionImpact={id:string;name:string;service:string;archived:boolean;matches:Array<{cueIds:string[]}>};
type CollectionImpactResolver=(cueIds:string[])=>Promise<CollectionImpact[]>;
export function createSourceReviewService(drafts:AuthoringRepository,reviews:SourceReviewRepository,collectionImpacts:CollectionImpactResolver=async()=>[]){
 return {async operation(operation:string,input:unknown,actor:string){const data=input&&typeof input==='object'&&!Array.isArray(input)?input as Record<string,unknown>:{};const only=(allowed:string[])=>{const extra=Object.keys(data).filter(key=>!allowed.includes(key));if(extra.length)throw new AuthoringError('invalid_input',`Input contains unsupported fields: ${extra.join(', ')}`)};
  if(operation==='scan'){only([]);const now=Date.now(),stored=await drafts.listDrafts(),existingIds=new Set(stored.map(draft=>draft.id)),candidates=[...stored,...baselineDrafts(existingIds,now)],records=candidates.flatMap(draft=>detectForDraft(draft,actor,now));for(const record of records)if(!existingIds.has(record.affected.draftId))record.priorDraft=clone(candidates.find(draft=>draft.id===record.affected.draftId)!);const publishedIds=[...new Set(records.filter(record=>record.affected.published).map(record=>record.affected.draftId))];const impacts=publishedIds.length?await collectionImpacts(publishedIds):[];for(const record of records)record.affected.serviceCollections=record.affected.published?impacts.filter(collection=>collection.id&&collection.name&&collection.matches.some(match=>match.cueIds.includes(record.affected.draftId))).map(({id,name,service,archived})=>({id,name,service,archived})):[];await reviews.upsert(records);return {detected:records.length,coverage:{authoredDrafts:stored.length,unopenedPublished:baselineCoverage(existingIds)},records:(await reviews.list()).map(summary)}}
  if(operation==='list'){only([]);const stored=await drafts.listDrafts();return {coverage:{authoredDrafts:stored.length,unopenedPublished:baselineCoverage(new Set(stored.map(draft=>draft.id)))},records:(await reviews.list()).map(summary)}}
  if(operation==='get'){only(['id']);if(typeof data.id!=='string'||!data.id)throw new AuthoringError('invalid_input','id is required');const record=await reviews.get(data.id);if(!record)throw new AuthoringError('unknown_source_change','Source change not found',404);return {record:publicRecord(record)}}
  if(operation==='decide'){only(['id','expectedVersion','decision','reason']);if(typeof data.id!=='string'||!data.id||!Number.isInteger(data.expectedVersion))throw new AuthoringError('invalid_input','id and expectedVersion are required');if(!['accept','defer','reject'].includes(String(data.decision)))throw new AuthoringError('invalid_input','decision must be accept, defer, or reject');const kind=String(data.decision) as 'accept'|'defer'|'reject';const reason=typeof data.reason==='string'&&data.reason.trim()?data.reason.trim():null;if((kind==='defer'||kind==='reject')&&!reason)throw new AuthoringError('reason_required','A reason is required to defer or reject a source change');if(reason&&reason.length>500)throw new AuthoringError('invalid_input','reason must be 500 characters or fewer');const record=await reviews.get(data.id);if(!record||record.version!==data.expectedVersion)throw new AuthoringError('conflict','This source review changed elsewhere. Refresh and try again.',409);let draft:Draft|null=null;if(kind==='accept'){if(record.comparison!=='exact'||record.blockedReason||!record.proposedSource)throw new AuthoringError('source_update_blocked',record.blockedReason??'Exact historical source text is unavailable',409);const storedOriginal=await drafts.getDraft(record.affected.draftId),original=storedOriginal??record.priorDraft;if(!original)throw new AuthoringError('source_history_unavailable','Affected source history is unavailable',409);if(storedOriginal&&(original.version!==record.affected.draftVersion||original.sourcePin.unitSha256[record.sourceId]!==record.fromUnitSha256))throw new AuthoringError('stale_source_review','The affected draft or source selection changed after this review was created. Scan sources again before accepting.',409);const oldSnapshots=original.sourceSnapshots?.length?clone(original.sourceSnapshots):sourceSnapshotsFor(original.content);const snapshots=oldSnapshots.map(source=>source.id===record.sourceId?clone(record.proposedSource!):source);if(!snapshots.some(source=>source.id===record.sourceId))snapshots.push(clone(record.proposedSource));const content=updatedVariantContent(original.content,record.sourceId,record.proposedSource);const editable=parseEditable({...editableOnly(original),name:`${original.name} — source update`.slice(0,80),content},false,snapshots) as EditableDraft;const now=Date.now();draft={...editable,id:randomUUID(),version:1,sourcePin:sourcePinFor(content,snapshots,record.toFeedSha256),sourceSnapshots:snapshots,activeRevision:null,activeDraftVersion:null,createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor}}
   const at=Date.now();const decision={kind:kind==='accept'?'accepted' as const:kind==='defer'?'deferred' as const:'rejected' as const,reason,actor,at,createdDraftId:draft?.id??null};const result=await reviews.decide(record.id,record.version,decision,draft);return {record:summary(result.record),draft:result.draft}}
  throw new AuthoringError('unknown_operation',`Unknown source review operation: ${operation}`,404)} };
}

function editableOnly(draft:Draft):EditableDraft{return {name:draft.name,title:draft.title,accentTitle:draft.accentTitle,layout:draft.layout,templateCueId:draft.templateCueId,content:clone(draft.content),presentation:clone(draft.presentation)}}
let defaultService:ReturnType<typeof createSourceReviewService>|undefined;
export function sourceReviewOperation(operation:string,input:unknown,actor:string){if(!defaultService){const drafts=authoringRepository(),workspace=authoringRepositoryMode(process.env),collections:CollectionImpactResolver=async ids=>(await import('./service-collections')).collectionsContainingCueIds(ids).then(items=>items.map(({id,name,service,archived,matches})=>({id,name,service,archived,matches:matches.map(match=>({cueIds:match.cueIds}))})));defaultService=createSourceReviewService(drafts,workspace.storage==='memory'?new MemorySourceReviewRepository(drafts):new PgSourceReviewRepository(),collections)}return defaultService.operation(operation,input,actor)}
