"use client";

import { Archive, ArchiveRestore, Check, FilePlus2, LoaderCircle, RotateCcw } from "lucide-react";
import { useState } from "react";
import { layoutLabel } from "@/lib/layout-label";
import type { PublicWorkspace } from "@/lib/workspace";
import type { DraftForm, Layout, TemplateSummary } from "./types";

export type WorkspaceAsset = { id: string; name: string; altText: string; mimeType: string; bytes: number; width: number; height: number; version: number; archived: boolean; published: boolean; privatePreviewUrl: string; publicUrl?: string };

export const densityOptions = [
  { id: "comfortable", label: "Comfortable", value: {} },
  { id: "large", label: "Large print", value: { hebrewFontSize: 42, transliterationFontSize: 35, titleFontSize: 34 } },
  { id: "compact", label: "Compact", value: { hebrewFontSize: 34, transliterationFontSize: 28, titleFontSize: 28 } },
] as const;

export function AppearanceEditor({ form, templates, selectedDensity, changeForm, workspace, assets, assetError, busy, uploadAsset, setAssetArchived, showArchivedAssets, setShowArchivedAssets }: { form: DraftForm; templates: TemplateSummary[]; selectedDensity: string; changeForm: (patch: Partial<DraftForm>) => void; workspace: PublicWorkspace | null; assets: WorkspaceAsset[]; assetError: string; busy: string; uploadAsset: (file: File, name: string, altText: string) => Promise<WorkspaceAsset>; setAssetArchived: (asset: WorkspaceAsset, archived: boolean) => void; showArchivedAssets: boolean; setShowArchivedAssets: (value: boolean) => void }) {
  const setPresentation = (patch: Partial<DraftForm["presentation"]>) => changeForm({ presentation: { ...form.presentation, ...patch } });
  const clearField = (field: keyof DraftForm["presentation"]) => { const next = { ...form.presentation }; delete next[field]; changeForm({ presentation: next }); };
  return <section className="form-section appearance-section"><div className="section-heading"><span>3</span><div><h3>Choose a look</h3><p>Every option uses approved motion and safe areas.</p></div></div><div className="layout-toggle" role="group" aria-label="Graphic layout">{(["left", "bottom", "right"] as Layout[]).map((layout) => <button key={layout} className={form.layout === layout ? "active" : ""} onClick={() => { const template = templates.find((item) => item.layout === layout && item.importable); changeForm({ layout, templateCueId: template?.id || "" }); }}>{layoutLabel(layout)}</button>)}</div>{form.mode === "custom" ? <p className="automatic-style">The broadcast-safe house style is selected automatically for this layout.</p> : <div className="template-gallery">{templates.filter((item) => item.layout === form.layout && item.importable).slice(0, 6).map((item) => <button key={item.id} className={form.templateCueId === item.id ? "selected" : ""} onClick={() => changeForm({ templateCueId: item.id })}><span className={`template-thumb ${item.layout}`}><span><i>כותרת</i><b>{form.title || "Prayer title"}</b><small>{form.mode === "bilingual" ? "Hebrew · Transliteration" : "English reading"}</small></span></span><span><strong>{item.name}</strong><small>{layoutLabel(item.layout)}</small></span>{form.templateCueId === item.id && <Check size={16} />}</button>)}</div>}
    <div className="appearance-controls"><fieldset><legend>Text density</legend><div>{densityOptions.map((option) => <button key={option.id} type="button" aria-pressed={selectedDensity === option.id} className={selectedDensity === option.id ? "active" : ""} onClick={() => changeForm({ presentation: { ...form.presentation, ...option.value, ...(option.id === "comfortable" ? { hebrewFontSize: undefined, transliterationFontSize: undefined, titleFontSize: undefined } : {}) } })}>{option.label}</button>)}</div></fieldset><fieldset><legend>Alignment</legend><div><button type="button" aria-pressed={!form.presentation.alignment} className={!form.presentation.alignment ? "active" : ""} onClick={() => clearField("alignment")}>Template default</button><button type="button" aria-pressed={form.presentation.alignment === "start"} className={form.presentation.alignment === "start" ? "active" : ""} onClick={() => setPresentation({ alignment: "start" })}>Logical start</button><button type="button" aria-pressed={form.presentation.alignment === "center"} className={form.presentation.alignment === "center" ? "active" : ""} onClick={() => setPresentation({ alignment: "center" })}>Centered</button></div><p className="control-note">Logical start keeps Hebrew reading from the right and Latin text from the left.</p></fieldset><fieldset><legend>Line spacing</legend><div><button type="button" aria-pressed={!form.presentation.lineSpacing} className={!form.presentation.lineSpacing ? "active" : ""} onClick={() => clearField("lineSpacing")}>Template default</button><button type="button" aria-pressed={form.presentation.lineSpacing === "compact"} className={form.presentation.lineSpacing === "compact" ? "active" : ""} onClick={() => setPresentation({ lineSpacing: "compact" })}>Compact</button><button type="button" aria-pressed={form.presentation.lineSpacing === "spacious"} className={form.presentation.lineSpacing === "spacious" ? "active" : ""} onClick={() => setPresentation({ lineSpacing: "spacious" })}>Spacious</button></div></fieldset></div>
    <ArtworkPicker workspace={workspace} assets={assets} selectedId={form.presentation.imageAssetId} error={assetError} busy={busy} select={(id) => id ? setPresentation({ imageAssetId: id }) : clearField("imageAssetId")} uploadAsset={uploadAsset} setAssetArchived={setAssetArchived} showArchived={showArchivedAssets} setShowArchived={setShowArchivedAssets} />
    <button className="reset-appearance" onClick={() => changeForm({ presentation: {} })}><RotateCcw size={15} /> Reset visual settings to template</button>
  </section>;
}

function ArtworkPicker({ workspace, assets, selectedId, error, busy, select, uploadAsset, setAssetArchived, showArchived, setShowArchived }: { workspace: PublicWorkspace | null; assets: WorkspaceAsset[]; selectedId?: string; error: string; busy: string; select: (id?: string) => void; uploadAsset: (file: File, name: string, altText: string) => Promise<WorkspaceAsset>; setAssetArchived: (asset: WorkspaceAsset, archived: boolean) => void; showArchived: boolean; setShowArchived: (value: boolean) => void }) {
  const [file, setFile] = useState<File | null>(null), [name, setName] = useState(""), [altText, setAltText] = useState(""), [uploadError, setUploadError] = useState("");
  // eslint-disable-next-line @next/next/no-img-element -- Asset thumbnails use authenticated, no-store URLs and must not pass through Next's public image optimizer.
  return <div className="artwork-picker"><div className="artwork-heading"><span><strong>Upper-right artwork</strong><small>Replaces the congregation logo only. Images stay inside the approved region.</small></span><button type="button" className="artwork-archived-toggle" aria-pressed={showArchived} onClick={() => setShowArchived(!showArchived)}>{showArchived ? "Hide archived" : "Show archived"}</button></div><div className="artwork-grid"><button className={!selectedId ? "selected" : ""} onClick={() => select()}>{workspace?.logo.src ? <img src={workspace.logo.src} alt="" /> : <span className="artwork-placeholder" />}<span><strong>Congregation logo</strong><small>Template default</small></span>{!selectedId && <Check size={15} />}</button>{assets.map((asset) => <div key={asset.id} className={`artwork-tile${selectedId === asset.id ? " selected" : ""}${asset.archived ? " archived" : ""}`}><button className="artwork-choice" onClick={() => select(asset.id)} disabled={asset.archived}><img src={asset.privatePreviewUrl} alt="" /><span><strong>{asset.name}</strong><small>{asset.archived ? "Archived · " : ""}{asset.width} × {asset.height} · {Math.ceil(asset.bytes / 1024)} KB</small></span>{selectedId === asset.id && <Check size={15} />}</button><button className="icon-button artwork-action" aria-label={`${asset.archived ? "Restore" : "Archive"} ${asset.name}`} title={asset.archived ? "Restore" : "Archive"} disabled={busy === "archive-asset" || busy === "restore-asset"} onClick={() => setAssetArchived(asset, !asset.archived)}>{asset.archived ? <ArchiveRestore size={14} /> : <Archive size={14} />}</button></div>)}</div>{error && <p className="asset-error">{error}</p>}<details className="asset-upload"><summary>Upload approved artwork</summary><p>PNG, JPEG, or WebP · up to 512 KB and 4096 pixels. Still images only.</p><div className="asset-upload-fields"><label>Image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const next = event.target.files?.[0] || null; setFile(next); if (next && !name) setName(next.name.replace(/\.[^.]+$/, "")); }} /></label><label>Name<input value={name} maxLength={80} onChange={(event) => setName(event.target.value)} /></label><label>Accessible description<input value={altText} maxLength={180} onChange={(event) => setAltText(event.target.value)} placeholder="Describe the image itself" /></label><button className="primary-button" disabled={!file || !name.trim() || !altText.trim() || busy === "upload-asset"} onClick={() => { if (!file) return; setUploadError(""); void uploadAsset(file, name, altText).then(() => { setFile(null); setName(""); setAltText(""); }).catch((value) => setUploadError(value instanceof Error ? value.message : "Artwork upload failed.")); }}>{busy === "upload-asset" ? <LoaderCircle className="spin" size={16} /> : <FilePlus2 size={16} />} Upload and select</button></div>{uploadError && <p className="asset-error">{uploadError}</p>}</details></div>;
}
